// -------------------------------------------------------------
// 
// File Name: hdlsrc\fft_new\MATLAB_Bit_Slice.v
// Created: 2025-06-03 11:25:57
// 
// Generated by MATLAB 9.12 and HDL Coder 3.20
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: MATLAB_Bit_Slice
// Source Path: fft_new/fft_sub1/For Each Subsystem/MATLAB Bit Slice
// Hierarchy Level: 3
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module MATLAB_Bit_Slice
          (u,
           n,
           NFFT,
           y);


  input   [8:0] u;  // ufix9
  input   [9:0] n;  // ufix10
  input   [7:0] NFFT;  // uint8
  output  y;  // ufix1


  reg  y_1;  // ufix1
  reg [10:0] c;  // ufix11
  reg [7:0] a;  // ufix8
  reg [7:0] bit_idx;  // uint8
  reg signed [11:0] sub_temp;  // sfix12
  reg signed [16:0] sub_temp_0;  // sfix17
  reg [10:0] t_0;  // ufix11
  reg signed [11:0] t_1;  // sfix12
  reg [10:0] t_2;  // ufix11
  reg signed [11:0] t_3;  // sfix12
  reg [15:0] t_4;  // uint16
  reg signed [16:0] t_5;  // sfix17


  always @(NFFT, n, u) begin
    sub_temp_0 = 17'sb00000000000000000;
    t_4 = 16'd0;
    t_5 = 17'sb00000000000000000;
    bit_idx = 8'd0;
    a = NFFT;
    t_0 = {3'b0, a};
    t_1 = {1'b0, t_0};
    t_2 = {1'b0, n};
    t_3 = {1'b0, t_2};
    sub_temp = t_1 - t_3;
    if (sub_temp[11] == 1'b1) begin
      c = 11'b00000000000;
    end
    else begin
      c = sub_temp[10:0];
    end
    if ((c >= 11'b00000000001) && (c <= 11'b00000001001)) begin
      t_4 = {5'b0, c};
      t_5 = {1'b0, t_4};
      sub_temp_0 = t_5 - 17'sb00000000000000001;
      if ((sub_temp_0[16] == 1'b0) && (sub_temp_0[15:8] != 8'b00000000)) begin
        bit_idx = 8'b11111111;
      end
      else if (sub_temp_0[16] == 1'b1) begin
        bit_idx = 8'b00000000;
      end
      else begin
        bit_idx = sub_temp_0[7:0];
      end
      y_1 = u[bit_idx];
    end
    else begin
      y_1 = 1'b0;
    end
  end



  assign y = y_1;

endmodule  // MATLAB_Bit_Slice

