// -------------------------------------------------------------
// 
// File Name: hdlsrc\fft_new\For_Each_Subsystem1.v
// Created: 2025-06-03 14:06:56
// 
// Generated by MATLAB 9.12 and HDL Coder 3.20
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: For_Each_Subsystem1
// Source Path: fft_new/Subsystem2/For Each Subsystem1
// Hierarchy Level: 2
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module For_Each_Subsystem1
          (clk,
           reset,
           enb,
           DATA_DELAY,
           DELAY_CAUNT,
           ENA,
           COUNT);


  input   clk;
  input   reset;
  input   enb;
  input   [6:0] DATA_DELAY;  // ufix7
  input   [7:0] DELAY_CAUNT;  // uint8
  input   ENA;
  output  [6:0] COUNT;  // ufix7


  wire [7:0] ctrlSat;  // uint8
  wire [7:0] controlSigOut;  // uint8
  reg [7:0] delayWire;  // uint8
  reg [6:0] Delay3_bypass [0:127];  // ufix7 [128]
  reg [6:0] Delay3_reg [0:127];  // ufix7 [128]
  wire [6:0] Delay3_bypass_next [0:127];  // ufix7 [128]
  wire [6:0] Delay3_reg_next [0:127];  // ufix7 [128]
  wire [6:0] delayTapWire [0:128];  // ufix7 [129]
  wire [6:0] Delay3_out1;  // ufix7


  assign ctrlSat = (DELAY_CAUNT > 8'b10000000 ? 8'b10000000 :
              DELAY_CAUNT);



  always @(posedge clk or posedge reset)
    begin : delayControlSig_process
      if (reset == 1'b1) begin
        delayWire <= 8'b00000000;
      end
      else begin
        if (enb) begin
          delayWire <= controlSigOut;
        end
      end
    end



  assign controlSigOut = (ENA == 1'b0 ? delayWire :
              ctrlSat);



  always @(posedge clk or posedge reset)
    begin : Delay3_process
      if (reset == 1'b1) begin
        Delay3_bypass[0] <= 7'b0000000;
        Delay3_bypass[1] <= 7'b0000000;
        Delay3_bypass[2] <= 7'b0000000;
        Delay3_bypass[3] <= 7'b0000000;
        Delay3_bypass[4] <= 7'b0000000;
        Delay3_bypass[5] <= 7'b0000000;
        Delay3_bypass[6] <= 7'b0000000;
        Delay3_bypass[7] <= 7'b0000000;
        Delay3_bypass[8] <= 7'b0000000;
        Delay3_bypass[9] <= 7'b0000000;
        Delay3_bypass[10] <= 7'b0000000;
        Delay3_bypass[11] <= 7'b0000000;
        Delay3_bypass[12] <= 7'b0000000;
        Delay3_bypass[13] <= 7'b0000000;
        Delay3_bypass[14] <= 7'b0000000;
        Delay3_bypass[15] <= 7'b0000000;
        Delay3_bypass[16] <= 7'b0000000;
        Delay3_bypass[17] <= 7'b0000000;
        Delay3_bypass[18] <= 7'b0000000;
        Delay3_bypass[19] <= 7'b0000000;
        Delay3_bypass[20] <= 7'b0000000;
        Delay3_bypass[21] <= 7'b0000000;
        Delay3_bypass[22] <= 7'b0000000;
        Delay3_bypass[23] <= 7'b0000000;
        Delay3_bypass[24] <= 7'b0000000;
        Delay3_bypass[25] <= 7'b0000000;
        Delay3_bypass[26] <= 7'b0000000;
        Delay3_bypass[27] <= 7'b0000000;
        Delay3_bypass[28] <= 7'b0000000;
        Delay3_bypass[29] <= 7'b0000000;
        Delay3_bypass[30] <= 7'b0000000;
        Delay3_bypass[31] <= 7'b0000000;
        Delay3_bypass[32] <= 7'b0000000;
        Delay3_bypass[33] <= 7'b0000000;
        Delay3_bypass[34] <= 7'b0000000;
        Delay3_bypass[35] <= 7'b0000000;
        Delay3_bypass[36] <= 7'b0000000;
        Delay3_bypass[37] <= 7'b0000000;
        Delay3_bypass[38] <= 7'b0000000;
        Delay3_bypass[39] <= 7'b0000000;
        Delay3_bypass[40] <= 7'b0000000;
        Delay3_bypass[41] <= 7'b0000000;
        Delay3_bypass[42] <= 7'b0000000;
        Delay3_bypass[43] <= 7'b0000000;
        Delay3_bypass[44] <= 7'b0000000;
        Delay3_bypass[45] <= 7'b0000000;
        Delay3_bypass[46] <= 7'b0000000;
        Delay3_bypass[47] <= 7'b0000000;
        Delay3_bypass[48] <= 7'b0000000;
        Delay3_bypass[49] <= 7'b0000000;
        Delay3_bypass[50] <= 7'b0000000;
        Delay3_bypass[51] <= 7'b0000000;
        Delay3_bypass[52] <= 7'b0000000;
        Delay3_bypass[53] <= 7'b0000000;
        Delay3_bypass[54] <= 7'b0000000;
        Delay3_bypass[55] <= 7'b0000000;
        Delay3_bypass[56] <= 7'b0000000;
        Delay3_bypass[57] <= 7'b0000000;
        Delay3_bypass[58] <= 7'b0000000;
        Delay3_bypass[59] <= 7'b0000000;
        Delay3_bypass[60] <= 7'b0000000;
        Delay3_bypass[61] <= 7'b0000000;
        Delay3_bypass[62] <= 7'b0000000;
        Delay3_bypass[63] <= 7'b0000000;
        Delay3_bypass[64] <= 7'b0000000;
        Delay3_bypass[65] <= 7'b0000000;
        Delay3_bypass[66] <= 7'b0000000;
        Delay3_bypass[67] <= 7'b0000000;
        Delay3_bypass[68] <= 7'b0000000;
        Delay3_bypass[69] <= 7'b0000000;
        Delay3_bypass[70] <= 7'b0000000;
        Delay3_bypass[71] <= 7'b0000000;
        Delay3_bypass[72] <= 7'b0000000;
        Delay3_bypass[73] <= 7'b0000000;
        Delay3_bypass[74] <= 7'b0000000;
        Delay3_bypass[75] <= 7'b0000000;
        Delay3_bypass[76] <= 7'b0000000;
        Delay3_bypass[77] <= 7'b0000000;
        Delay3_bypass[78] <= 7'b0000000;
        Delay3_bypass[79] <= 7'b0000000;
        Delay3_bypass[80] <= 7'b0000000;
        Delay3_bypass[81] <= 7'b0000000;
        Delay3_bypass[82] <= 7'b0000000;
        Delay3_bypass[83] <= 7'b0000000;
        Delay3_bypass[84] <= 7'b0000000;
        Delay3_bypass[85] <= 7'b0000000;
        Delay3_bypass[86] <= 7'b0000000;
        Delay3_bypass[87] <= 7'b0000000;
        Delay3_bypass[88] <= 7'b0000000;
        Delay3_bypass[89] <= 7'b0000000;
        Delay3_bypass[90] <= 7'b0000000;
        Delay3_bypass[91] <= 7'b0000000;
        Delay3_bypass[92] <= 7'b0000000;
        Delay3_bypass[93] <= 7'b0000000;
        Delay3_bypass[94] <= 7'b0000000;
        Delay3_bypass[95] <= 7'b0000000;
        Delay3_bypass[96] <= 7'b0000000;
        Delay3_bypass[97] <= 7'b0000000;
        Delay3_bypass[98] <= 7'b0000000;
        Delay3_bypass[99] <= 7'b0000000;
        Delay3_bypass[100] <= 7'b0000000;
        Delay3_bypass[101] <= 7'b0000000;
        Delay3_bypass[102] <= 7'b0000000;
        Delay3_bypass[103] <= 7'b0000000;
        Delay3_bypass[104] <= 7'b0000000;
        Delay3_bypass[105] <= 7'b0000000;
        Delay3_bypass[106] <= 7'b0000000;
        Delay3_bypass[107] <= 7'b0000000;
        Delay3_bypass[108] <= 7'b0000000;
        Delay3_bypass[109] <= 7'b0000000;
        Delay3_bypass[110] <= 7'b0000000;
        Delay3_bypass[111] <= 7'b0000000;
        Delay3_bypass[112] <= 7'b0000000;
        Delay3_bypass[113] <= 7'b0000000;
        Delay3_bypass[114] <= 7'b0000000;
        Delay3_bypass[115] <= 7'b0000000;
        Delay3_bypass[116] <= 7'b0000000;
        Delay3_bypass[117] <= 7'b0000000;
        Delay3_bypass[118] <= 7'b0000000;
        Delay3_bypass[119] <= 7'b0000000;
        Delay3_bypass[120] <= 7'b0000000;
        Delay3_bypass[121] <= 7'b0000000;
        Delay3_bypass[122] <= 7'b0000000;
        Delay3_bypass[123] <= 7'b0000000;
        Delay3_bypass[124] <= 7'b0000000;
        Delay3_bypass[125] <= 7'b0000000;
        Delay3_bypass[126] <= 7'b0000000;
        Delay3_bypass[127] <= 7'b0000000;
        Delay3_reg[0] <= 7'b0000000;
        Delay3_reg[1] <= 7'b0000000;
        Delay3_reg[2] <= 7'b0000000;
        Delay3_reg[3] <= 7'b0000000;
        Delay3_reg[4] <= 7'b0000000;
        Delay3_reg[5] <= 7'b0000000;
        Delay3_reg[6] <= 7'b0000000;
        Delay3_reg[7] <= 7'b0000000;
        Delay3_reg[8] <= 7'b0000000;
        Delay3_reg[9] <= 7'b0000000;
        Delay3_reg[10] <= 7'b0000000;
        Delay3_reg[11] <= 7'b0000000;
        Delay3_reg[12] <= 7'b0000000;
        Delay3_reg[13] <= 7'b0000000;
        Delay3_reg[14] <= 7'b0000000;
        Delay3_reg[15] <= 7'b0000000;
        Delay3_reg[16] <= 7'b0000000;
        Delay3_reg[17] <= 7'b0000000;
        Delay3_reg[18] <= 7'b0000000;
        Delay3_reg[19] <= 7'b0000000;
        Delay3_reg[20] <= 7'b0000000;
        Delay3_reg[21] <= 7'b0000000;
        Delay3_reg[22] <= 7'b0000000;
        Delay3_reg[23] <= 7'b0000000;
        Delay3_reg[24] <= 7'b0000000;
        Delay3_reg[25] <= 7'b0000000;
        Delay3_reg[26] <= 7'b0000000;
        Delay3_reg[27] <= 7'b0000000;
        Delay3_reg[28] <= 7'b0000000;
        Delay3_reg[29] <= 7'b0000000;
        Delay3_reg[30] <= 7'b0000000;
        Delay3_reg[31] <= 7'b0000000;
        Delay3_reg[32] <= 7'b0000000;
        Delay3_reg[33] <= 7'b0000000;
        Delay3_reg[34] <= 7'b0000000;
        Delay3_reg[35] <= 7'b0000000;
        Delay3_reg[36] <= 7'b0000000;
        Delay3_reg[37] <= 7'b0000000;
        Delay3_reg[38] <= 7'b0000000;
        Delay3_reg[39] <= 7'b0000000;
        Delay3_reg[40] <= 7'b0000000;
        Delay3_reg[41] <= 7'b0000000;
        Delay3_reg[42] <= 7'b0000000;
        Delay3_reg[43] <= 7'b0000000;
        Delay3_reg[44] <= 7'b0000000;
        Delay3_reg[45] <= 7'b0000000;
        Delay3_reg[46] <= 7'b0000000;
        Delay3_reg[47] <= 7'b0000000;
        Delay3_reg[48] <= 7'b0000000;
        Delay3_reg[49] <= 7'b0000000;
        Delay3_reg[50] <= 7'b0000000;
        Delay3_reg[51] <= 7'b0000000;
        Delay3_reg[52] <= 7'b0000000;
        Delay3_reg[53] <= 7'b0000000;
        Delay3_reg[54] <= 7'b0000000;
        Delay3_reg[55] <= 7'b0000000;
        Delay3_reg[56] <= 7'b0000000;
        Delay3_reg[57] <= 7'b0000000;
        Delay3_reg[58] <= 7'b0000000;
        Delay3_reg[59] <= 7'b0000000;
        Delay3_reg[60] <= 7'b0000000;
        Delay3_reg[61] <= 7'b0000000;
        Delay3_reg[62] <= 7'b0000000;
        Delay3_reg[63] <= 7'b0000000;
        Delay3_reg[64] <= 7'b0000000;
        Delay3_reg[65] <= 7'b0000000;
        Delay3_reg[66] <= 7'b0000000;
        Delay3_reg[67] <= 7'b0000000;
        Delay3_reg[68] <= 7'b0000000;
        Delay3_reg[69] <= 7'b0000000;
        Delay3_reg[70] <= 7'b0000000;
        Delay3_reg[71] <= 7'b0000000;
        Delay3_reg[72] <= 7'b0000000;
        Delay3_reg[73] <= 7'b0000000;
        Delay3_reg[74] <= 7'b0000000;
        Delay3_reg[75] <= 7'b0000000;
        Delay3_reg[76] <= 7'b0000000;
        Delay3_reg[77] <= 7'b0000000;
        Delay3_reg[78] <= 7'b0000000;
        Delay3_reg[79] <= 7'b0000000;
        Delay3_reg[80] <= 7'b0000000;
        Delay3_reg[81] <= 7'b0000000;
        Delay3_reg[82] <= 7'b0000000;
        Delay3_reg[83] <= 7'b0000000;
        Delay3_reg[84] <= 7'b0000000;
        Delay3_reg[85] <= 7'b0000000;
        Delay3_reg[86] <= 7'b0000000;
        Delay3_reg[87] <= 7'b0000000;
        Delay3_reg[88] <= 7'b0000000;
        Delay3_reg[89] <= 7'b0000000;
        Delay3_reg[90] <= 7'b0000000;
        Delay3_reg[91] <= 7'b0000000;
        Delay3_reg[92] <= 7'b0000000;
        Delay3_reg[93] <= 7'b0000000;
        Delay3_reg[94] <= 7'b0000000;
        Delay3_reg[95] <= 7'b0000000;
        Delay3_reg[96] <= 7'b0000000;
        Delay3_reg[97] <= 7'b0000000;
        Delay3_reg[98] <= 7'b0000000;
        Delay3_reg[99] <= 7'b0000000;
        Delay3_reg[100] <= 7'b0000000;
        Delay3_reg[101] <= 7'b0000000;
        Delay3_reg[102] <= 7'b0000000;
        Delay3_reg[103] <= 7'b0000000;
        Delay3_reg[104] <= 7'b0000000;
        Delay3_reg[105] <= 7'b0000000;
        Delay3_reg[106] <= 7'b0000000;
        Delay3_reg[107] <= 7'b0000000;
        Delay3_reg[108] <= 7'b0000000;
        Delay3_reg[109] <= 7'b0000000;
        Delay3_reg[110] <= 7'b0000000;
        Delay3_reg[111] <= 7'b0000000;
        Delay3_reg[112] <= 7'b0000000;
        Delay3_reg[113] <= 7'b0000000;
        Delay3_reg[114] <= 7'b0000000;
        Delay3_reg[115] <= 7'b0000000;
        Delay3_reg[116] <= 7'b0000000;
        Delay3_reg[117] <= 7'b0000000;
        Delay3_reg[118] <= 7'b0000000;
        Delay3_reg[119] <= 7'b0000000;
        Delay3_reg[120] <= 7'b0000000;
        Delay3_reg[121] <= 7'b0000000;
        Delay3_reg[122] <= 7'b0000000;
        Delay3_reg[123] <= 7'b0000000;
        Delay3_reg[124] <= 7'b0000000;
        Delay3_reg[125] <= 7'b0000000;
        Delay3_reg[126] <= 7'b0000000;
        Delay3_reg[127] <= 7'b0000000;
      end
      else begin
        if (enb && ENA) begin
          Delay3_bypass[0] <= Delay3_bypass_next[0];
          Delay3_bypass[1] <= Delay3_bypass_next[1];
          Delay3_bypass[2] <= Delay3_bypass_next[2];
          Delay3_bypass[3] <= Delay3_bypass_next[3];
          Delay3_bypass[4] <= Delay3_bypass_next[4];
          Delay3_bypass[5] <= Delay3_bypass_next[5];
          Delay3_bypass[6] <= Delay3_bypass_next[6];
          Delay3_bypass[7] <= Delay3_bypass_next[7];
          Delay3_bypass[8] <= Delay3_bypass_next[8];
          Delay3_bypass[9] <= Delay3_bypass_next[9];
          Delay3_bypass[10] <= Delay3_bypass_next[10];
          Delay3_bypass[11] <= Delay3_bypass_next[11];
          Delay3_bypass[12] <= Delay3_bypass_next[12];
          Delay3_bypass[13] <= Delay3_bypass_next[13];
          Delay3_bypass[14] <= Delay3_bypass_next[14];
          Delay3_bypass[15] <= Delay3_bypass_next[15];
          Delay3_bypass[16] <= Delay3_bypass_next[16];
          Delay3_bypass[17] <= Delay3_bypass_next[17];
          Delay3_bypass[18] <= Delay3_bypass_next[18];
          Delay3_bypass[19] <= Delay3_bypass_next[19];
          Delay3_bypass[20] <= Delay3_bypass_next[20];
          Delay3_bypass[21] <= Delay3_bypass_next[21];
          Delay3_bypass[22] <= Delay3_bypass_next[22];
          Delay3_bypass[23] <= Delay3_bypass_next[23];
          Delay3_bypass[24] <= Delay3_bypass_next[24];
          Delay3_bypass[25] <= Delay3_bypass_next[25];
          Delay3_bypass[26] <= Delay3_bypass_next[26];
          Delay3_bypass[27] <= Delay3_bypass_next[27];
          Delay3_bypass[28] <= Delay3_bypass_next[28];
          Delay3_bypass[29] <= Delay3_bypass_next[29];
          Delay3_bypass[30] <= Delay3_bypass_next[30];
          Delay3_bypass[31] <= Delay3_bypass_next[31];
          Delay3_bypass[32] <= Delay3_bypass_next[32];
          Delay3_bypass[33] <= Delay3_bypass_next[33];
          Delay3_bypass[34] <= Delay3_bypass_next[34];
          Delay3_bypass[35] <= Delay3_bypass_next[35];
          Delay3_bypass[36] <= Delay3_bypass_next[36];
          Delay3_bypass[37] <= Delay3_bypass_next[37];
          Delay3_bypass[38] <= Delay3_bypass_next[38];
          Delay3_bypass[39] <= Delay3_bypass_next[39];
          Delay3_bypass[40] <= Delay3_bypass_next[40];
          Delay3_bypass[41] <= Delay3_bypass_next[41];
          Delay3_bypass[42] <= Delay3_bypass_next[42];
          Delay3_bypass[43] <= Delay3_bypass_next[43];
          Delay3_bypass[44] <= Delay3_bypass_next[44];
          Delay3_bypass[45] <= Delay3_bypass_next[45];
          Delay3_bypass[46] <= Delay3_bypass_next[46];
          Delay3_bypass[47] <= Delay3_bypass_next[47];
          Delay3_bypass[48] <= Delay3_bypass_next[48];
          Delay3_bypass[49] <= Delay3_bypass_next[49];
          Delay3_bypass[50] <= Delay3_bypass_next[50];
          Delay3_bypass[51] <= Delay3_bypass_next[51];
          Delay3_bypass[52] <= Delay3_bypass_next[52];
          Delay3_bypass[53] <= Delay3_bypass_next[53];
          Delay3_bypass[54] <= Delay3_bypass_next[54];
          Delay3_bypass[55] <= Delay3_bypass_next[55];
          Delay3_bypass[56] <= Delay3_bypass_next[56];
          Delay3_bypass[57] <= Delay3_bypass_next[57];
          Delay3_bypass[58] <= Delay3_bypass_next[58];
          Delay3_bypass[59] <= Delay3_bypass_next[59];
          Delay3_bypass[60] <= Delay3_bypass_next[60];
          Delay3_bypass[61] <= Delay3_bypass_next[61];
          Delay3_bypass[62] <= Delay3_bypass_next[62];
          Delay3_bypass[63] <= Delay3_bypass_next[63];
          Delay3_bypass[64] <= Delay3_bypass_next[64];
          Delay3_bypass[65] <= Delay3_bypass_next[65];
          Delay3_bypass[66] <= Delay3_bypass_next[66];
          Delay3_bypass[67] <= Delay3_bypass_next[67];
          Delay3_bypass[68] <= Delay3_bypass_next[68];
          Delay3_bypass[69] <= Delay3_bypass_next[69];
          Delay3_bypass[70] <= Delay3_bypass_next[70];
          Delay3_bypass[71] <= Delay3_bypass_next[71];
          Delay3_bypass[72] <= Delay3_bypass_next[72];
          Delay3_bypass[73] <= Delay3_bypass_next[73];
          Delay3_bypass[74] <= Delay3_bypass_next[74];
          Delay3_bypass[75] <= Delay3_bypass_next[75];
          Delay3_bypass[76] <= Delay3_bypass_next[76];
          Delay3_bypass[77] <= Delay3_bypass_next[77];
          Delay3_bypass[78] <= Delay3_bypass_next[78];
          Delay3_bypass[79] <= Delay3_bypass_next[79];
          Delay3_bypass[80] <= Delay3_bypass_next[80];
          Delay3_bypass[81] <= Delay3_bypass_next[81];
          Delay3_bypass[82] <= Delay3_bypass_next[82];
          Delay3_bypass[83] <= Delay3_bypass_next[83];
          Delay3_bypass[84] <= Delay3_bypass_next[84];
          Delay3_bypass[85] <= Delay3_bypass_next[85];
          Delay3_bypass[86] <= Delay3_bypass_next[86];
          Delay3_bypass[87] <= Delay3_bypass_next[87];
          Delay3_bypass[88] <= Delay3_bypass_next[88];
          Delay3_bypass[89] <= Delay3_bypass_next[89];
          Delay3_bypass[90] <= Delay3_bypass_next[90];
          Delay3_bypass[91] <= Delay3_bypass_next[91];
          Delay3_bypass[92] <= Delay3_bypass_next[92];
          Delay3_bypass[93] <= Delay3_bypass_next[93];
          Delay3_bypass[94] <= Delay3_bypass_next[94];
          Delay3_bypass[95] <= Delay3_bypass_next[95];
          Delay3_bypass[96] <= Delay3_bypass_next[96];
          Delay3_bypass[97] <= Delay3_bypass_next[97];
          Delay3_bypass[98] <= Delay3_bypass_next[98];
          Delay3_bypass[99] <= Delay3_bypass_next[99];
          Delay3_bypass[100] <= Delay3_bypass_next[100];
          Delay3_bypass[101] <= Delay3_bypass_next[101];
          Delay3_bypass[102] <= Delay3_bypass_next[102];
          Delay3_bypass[103] <= Delay3_bypass_next[103];
          Delay3_bypass[104] <= Delay3_bypass_next[104];
          Delay3_bypass[105] <= Delay3_bypass_next[105];
          Delay3_bypass[106] <= Delay3_bypass_next[106];
          Delay3_bypass[107] <= Delay3_bypass_next[107];
          Delay3_bypass[108] <= Delay3_bypass_next[108];
          Delay3_bypass[109] <= Delay3_bypass_next[109];
          Delay3_bypass[110] <= Delay3_bypass_next[110];
          Delay3_bypass[111] <= Delay3_bypass_next[111];
          Delay3_bypass[112] <= Delay3_bypass_next[112];
          Delay3_bypass[113] <= Delay3_bypass_next[113];
          Delay3_bypass[114] <= Delay3_bypass_next[114];
          Delay3_bypass[115] <= Delay3_bypass_next[115];
          Delay3_bypass[116] <= Delay3_bypass_next[116];
          Delay3_bypass[117] <= Delay3_bypass_next[117];
          Delay3_bypass[118] <= Delay3_bypass_next[118];
          Delay3_bypass[119] <= Delay3_bypass_next[119];
          Delay3_bypass[120] <= Delay3_bypass_next[120];
          Delay3_bypass[121] <= Delay3_bypass_next[121];
          Delay3_bypass[122] <= Delay3_bypass_next[122];
          Delay3_bypass[123] <= Delay3_bypass_next[123];
          Delay3_bypass[124] <= Delay3_bypass_next[124];
          Delay3_bypass[125] <= Delay3_bypass_next[125];
          Delay3_bypass[126] <= Delay3_bypass_next[126];
          Delay3_bypass[127] <= Delay3_bypass_next[127];
          Delay3_reg[0] <= Delay3_reg_next[0];
          Delay3_reg[1] <= Delay3_reg_next[1];
          Delay3_reg[2] <= Delay3_reg_next[2];
          Delay3_reg[3] <= Delay3_reg_next[3];
          Delay3_reg[4] <= Delay3_reg_next[4];
          Delay3_reg[5] <= Delay3_reg_next[5];
          Delay3_reg[6] <= Delay3_reg_next[6];
          Delay3_reg[7] <= Delay3_reg_next[7];
          Delay3_reg[8] <= Delay3_reg_next[8];
          Delay3_reg[9] <= Delay3_reg_next[9];
          Delay3_reg[10] <= Delay3_reg_next[10];
          Delay3_reg[11] <= Delay3_reg_next[11];
          Delay3_reg[12] <= Delay3_reg_next[12];
          Delay3_reg[13] <= Delay3_reg_next[13];
          Delay3_reg[14] <= Delay3_reg_next[14];
          Delay3_reg[15] <= Delay3_reg_next[15];
          Delay3_reg[16] <= Delay3_reg_next[16];
          Delay3_reg[17] <= Delay3_reg_next[17];
          Delay3_reg[18] <= Delay3_reg_next[18];
          Delay3_reg[19] <= Delay3_reg_next[19];
          Delay3_reg[20] <= Delay3_reg_next[20];
          Delay3_reg[21] <= Delay3_reg_next[21];
          Delay3_reg[22] <= Delay3_reg_next[22];
          Delay3_reg[23] <= Delay3_reg_next[23];
          Delay3_reg[24] <= Delay3_reg_next[24];
          Delay3_reg[25] <= Delay3_reg_next[25];
          Delay3_reg[26] <= Delay3_reg_next[26];
          Delay3_reg[27] <= Delay3_reg_next[27];
          Delay3_reg[28] <= Delay3_reg_next[28];
          Delay3_reg[29] <= Delay3_reg_next[29];
          Delay3_reg[30] <= Delay3_reg_next[30];
          Delay3_reg[31] <= Delay3_reg_next[31];
          Delay3_reg[32] <= Delay3_reg_next[32];
          Delay3_reg[33] <= Delay3_reg_next[33];
          Delay3_reg[34] <= Delay3_reg_next[34];
          Delay3_reg[35] <= Delay3_reg_next[35];
          Delay3_reg[36] <= Delay3_reg_next[36];
          Delay3_reg[37] <= Delay3_reg_next[37];
          Delay3_reg[38] <= Delay3_reg_next[38];
          Delay3_reg[39] <= Delay3_reg_next[39];
          Delay3_reg[40] <= Delay3_reg_next[40];
          Delay3_reg[41] <= Delay3_reg_next[41];
          Delay3_reg[42] <= Delay3_reg_next[42];
          Delay3_reg[43] <= Delay3_reg_next[43];
          Delay3_reg[44] <= Delay3_reg_next[44];
          Delay3_reg[45] <= Delay3_reg_next[45];
          Delay3_reg[46] <= Delay3_reg_next[46];
          Delay3_reg[47] <= Delay3_reg_next[47];
          Delay3_reg[48] <= Delay3_reg_next[48];
          Delay3_reg[49] <= Delay3_reg_next[49];
          Delay3_reg[50] <= Delay3_reg_next[50];
          Delay3_reg[51] <= Delay3_reg_next[51];
          Delay3_reg[52] <= Delay3_reg_next[52];
          Delay3_reg[53] <= Delay3_reg_next[53];
          Delay3_reg[54] <= Delay3_reg_next[54];
          Delay3_reg[55] <= Delay3_reg_next[55];
          Delay3_reg[56] <= Delay3_reg_next[56];
          Delay3_reg[57] <= Delay3_reg_next[57];
          Delay3_reg[58] <= Delay3_reg_next[58];
          Delay3_reg[59] <= Delay3_reg_next[59];
          Delay3_reg[60] <= Delay3_reg_next[60];
          Delay3_reg[61] <= Delay3_reg_next[61];
          Delay3_reg[62] <= Delay3_reg_next[62];
          Delay3_reg[63] <= Delay3_reg_next[63];
          Delay3_reg[64] <= Delay3_reg_next[64];
          Delay3_reg[65] <= Delay3_reg_next[65];
          Delay3_reg[66] <= Delay3_reg_next[66];
          Delay3_reg[67] <= Delay3_reg_next[67];
          Delay3_reg[68] <= Delay3_reg_next[68];
          Delay3_reg[69] <= Delay3_reg_next[69];
          Delay3_reg[70] <= Delay3_reg_next[70];
          Delay3_reg[71] <= Delay3_reg_next[71];
          Delay3_reg[72] <= Delay3_reg_next[72];
          Delay3_reg[73] <= Delay3_reg_next[73];
          Delay3_reg[74] <= Delay3_reg_next[74];
          Delay3_reg[75] <= Delay3_reg_next[75];
          Delay3_reg[76] <= Delay3_reg_next[76];
          Delay3_reg[77] <= Delay3_reg_next[77];
          Delay3_reg[78] <= Delay3_reg_next[78];
          Delay3_reg[79] <= Delay3_reg_next[79];
          Delay3_reg[80] <= Delay3_reg_next[80];
          Delay3_reg[81] <= Delay3_reg_next[81];
          Delay3_reg[82] <= Delay3_reg_next[82];
          Delay3_reg[83] <= Delay3_reg_next[83];
          Delay3_reg[84] <= Delay3_reg_next[84];
          Delay3_reg[85] <= Delay3_reg_next[85];
          Delay3_reg[86] <= Delay3_reg_next[86];
          Delay3_reg[87] <= Delay3_reg_next[87];
          Delay3_reg[88] <= Delay3_reg_next[88];
          Delay3_reg[89] <= Delay3_reg_next[89];
          Delay3_reg[90] <= Delay3_reg_next[90];
          Delay3_reg[91] <= Delay3_reg_next[91];
          Delay3_reg[92] <= Delay3_reg_next[92];
          Delay3_reg[93] <= Delay3_reg_next[93];
          Delay3_reg[94] <= Delay3_reg_next[94];
          Delay3_reg[95] <= Delay3_reg_next[95];
          Delay3_reg[96] <= Delay3_reg_next[96];
          Delay3_reg[97] <= Delay3_reg_next[97];
          Delay3_reg[98] <= Delay3_reg_next[98];
          Delay3_reg[99] <= Delay3_reg_next[99];
          Delay3_reg[100] <= Delay3_reg_next[100];
          Delay3_reg[101] <= Delay3_reg_next[101];
          Delay3_reg[102] <= Delay3_reg_next[102];
          Delay3_reg[103] <= Delay3_reg_next[103];
          Delay3_reg[104] <= Delay3_reg_next[104];
          Delay3_reg[105] <= Delay3_reg_next[105];
          Delay3_reg[106] <= Delay3_reg_next[106];
          Delay3_reg[107] <= Delay3_reg_next[107];
          Delay3_reg[108] <= Delay3_reg_next[108];
          Delay3_reg[109] <= Delay3_reg_next[109];
          Delay3_reg[110] <= Delay3_reg_next[110];
          Delay3_reg[111] <= Delay3_reg_next[111];
          Delay3_reg[112] <= Delay3_reg_next[112];
          Delay3_reg[113] <= Delay3_reg_next[113];
          Delay3_reg[114] <= Delay3_reg_next[114];
          Delay3_reg[115] <= Delay3_reg_next[115];
          Delay3_reg[116] <= Delay3_reg_next[116];
          Delay3_reg[117] <= Delay3_reg_next[117];
          Delay3_reg[118] <= Delay3_reg_next[118];
          Delay3_reg[119] <= Delay3_reg_next[119];
          Delay3_reg[120] <= Delay3_reg_next[120];
          Delay3_reg[121] <= Delay3_reg_next[121];
          Delay3_reg[122] <= Delay3_reg_next[122];
          Delay3_reg[123] <= Delay3_reg_next[123];
          Delay3_reg[124] <= Delay3_reg_next[124];
          Delay3_reg[125] <= Delay3_reg_next[125];
          Delay3_reg[126] <= Delay3_reg_next[126];
          Delay3_reg[127] <= Delay3_reg_next[127];
        end
      end
    end

  assign delayTapWire[0] = (ENA == 1'b1 ? DATA_DELAY :
              Delay3_reg[0]);
  assign delayTapWire[1] = (ENA == 1'b1 ? Delay3_reg[0] :
              Delay3_bypass[0]);
  assign delayTapWire[2] = (ENA == 1'b1 ? Delay3_reg[1] :
              Delay3_bypass[1]);
  assign delayTapWire[3] = (ENA == 1'b1 ? Delay3_reg[2] :
              Delay3_bypass[2]);
  assign delayTapWire[4] = (ENA == 1'b1 ? Delay3_reg[3] :
              Delay3_bypass[3]);
  assign delayTapWire[5] = (ENA == 1'b1 ? Delay3_reg[4] :
              Delay3_bypass[4]);
  assign delayTapWire[6] = (ENA == 1'b1 ? Delay3_reg[5] :
              Delay3_bypass[5]);
  assign delayTapWire[7] = (ENA == 1'b1 ? Delay3_reg[6] :
              Delay3_bypass[6]);
  assign delayTapWire[8] = (ENA == 1'b1 ? Delay3_reg[7] :
              Delay3_bypass[7]);
  assign delayTapWire[9] = (ENA == 1'b1 ? Delay3_reg[8] :
              Delay3_bypass[8]);
  assign delayTapWire[10] = (ENA == 1'b1 ? Delay3_reg[9] :
              Delay3_bypass[9]);
  assign delayTapWire[11] = (ENA == 1'b1 ? Delay3_reg[10] :
              Delay3_bypass[10]);
  assign delayTapWire[12] = (ENA == 1'b1 ? Delay3_reg[11] :
              Delay3_bypass[11]);
  assign delayTapWire[13] = (ENA == 1'b1 ? Delay3_reg[12] :
              Delay3_bypass[12]);
  assign delayTapWire[14] = (ENA == 1'b1 ? Delay3_reg[13] :
              Delay3_bypass[13]);
  assign delayTapWire[15] = (ENA == 1'b1 ? Delay3_reg[14] :
              Delay3_bypass[14]);
  assign delayTapWire[16] = (ENA == 1'b1 ? Delay3_reg[15] :
              Delay3_bypass[15]);
  assign delayTapWire[17] = (ENA == 1'b1 ? Delay3_reg[16] :
              Delay3_bypass[16]);
  assign delayTapWire[18] = (ENA == 1'b1 ? Delay3_reg[17] :
              Delay3_bypass[17]);
  assign delayTapWire[19] = (ENA == 1'b1 ? Delay3_reg[18] :
              Delay3_bypass[18]);
  assign delayTapWire[20] = (ENA == 1'b1 ? Delay3_reg[19] :
              Delay3_bypass[19]);
  assign delayTapWire[21] = (ENA == 1'b1 ? Delay3_reg[20] :
              Delay3_bypass[20]);
  assign delayTapWire[22] = (ENA == 1'b1 ? Delay3_reg[21] :
              Delay3_bypass[21]);
  assign delayTapWire[23] = (ENA == 1'b1 ? Delay3_reg[22] :
              Delay3_bypass[22]);
  assign delayTapWire[24] = (ENA == 1'b1 ? Delay3_reg[23] :
              Delay3_bypass[23]);
  assign delayTapWire[25] = (ENA == 1'b1 ? Delay3_reg[24] :
              Delay3_bypass[24]);
  assign delayTapWire[26] = (ENA == 1'b1 ? Delay3_reg[25] :
              Delay3_bypass[25]);
  assign delayTapWire[27] = (ENA == 1'b1 ? Delay3_reg[26] :
              Delay3_bypass[26]);
  assign delayTapWire[28] = (ENA == 1'b1 ? Delay3_reg[27] :
              Delay3_bypass[27]);
  assign delayTapWire[29] = (ENA == 1'b1 ? Delay3_reg[28] :
              Delay3_bypass[28]);
  assign delayTapWire[30] = (ENA == 1'b1 ? Delay3_reg[29] :
              Delay3_bypass[29]);
  assign delayTapWire[31] = (ENA == 1'b1 ? Delay3_reg[30] :
              Delay3_bypass[30]);
  assign delayTapWire[32] = (ENA == 1'b1 ? Delay3_reg[31] :
              Delay3_bypass[31]);
  assign delayTapWire[33] = (ENA == 1'b1 ? Delay3_reg[32] :
              Delay3_bypass[32]);
  assign delayTapWire[34] = (ENA == 1'b1 ? Delay3_reg[33] :
              Delay3_bypass[33]);
  assign delayTapWire[35] = (ENA == 1'b1 ? Delay3_reg[34] :
              Delay3_bypass[34]);
  assign delayTapWire[36] = (ENA == 1'b1 ? Delay3_reg[35] :
              Delay3_bypass[35]);
  assign delayTapWire[37] = (ENA == 1'b1 ? Delay3_reg[36] :
              Delay3_bypass[36]);
  assign delayTapWire[38] = (ENA == 1'b1 ? Delay3_reg[37] :
              Delay3_bypass[37]);
  assign delayTapWire[39] = (ENA == 1'b1 ? Delay3_reg[38] :
              Delay3_bypass[38]);
  assign delayTapWire[40] = (ENA == 1'b1 ? Delay3_reg[39] :
              Delay3_bypass[39]);
  assign delayTapWire[41] = (ENA == 1'b1 ? Delay3_reg[40] :
              Delay3_bypass[40]);
  assign delayTapWire[42] = (ENA == 1'b1 ? Delay3_reg[41] :
              Delay3_bypass[41]);
  assign delayTapWire[43] = (ENA == 1'b1 ? Delay3_reg[42] :
              Delay3_bypass[42]);
  assign delayTapWire[44] = (ENA == 1'b1 ? Delay3_reg[43] :
              Delay3_bypass[43]);
  assign delayTapWire[45] = (ENA == 1'b1 ? Delay3_reg[44] :
              Delay3_bypass[44]);
  assign delayTapWire[46] = (ENA == 1'b1 ? Delay3_reg[45] :
              Delay3_bypass[45]);
  assign delayTapWire[47] = (ENA == 1'b1 ? Delay3_reg[46] :
              Delay3_bypass[46]);
  assign delayTapWire[48] = (ENA == 1'b1 ? Delay3_reg[47] :
              Delay3_bypass[47]);
  assign delayTapWire[49] = (ENA == 1'b1 ? Delay3_reg[48] :
              Delay3_bypass[48]);
  assign delayTapWire[50] = (ENA == 1'b1 ? Delay3_reg[49] :
              Delay3_bypass[49]);
  assign delayTapWire[51] = (ENA == 1'b1 ? Delay3_reg[50] :
              Delay3_bypass[50]);
  assign delayTapWire[52] = (ENA == 1'b1 ? Delay3_reg[51] :
              Delay3_bypass[51]);
  assign delayTapWire[53] = (ENA == 1'b1 ? Delay3_reg[52] :
              Delay3_bypass[52]);
  assign delayTapWire[54] = (ENA == 1'b1 ? Delay3_reg[53] :
              Delay3_bypass[53]);
  assign delayTapWire[55] = (ENA == 1'b1 ? Delay3_reg[54] :
              Delay3_bypass[54]);
  assign delayTapWire[56] = (ENA == 1'b1 ? Delay3_reg[55] :
              Delay3_bypass[55]);
  assign delayTapWire[57] = (ENA == 1'b1 ? Delay3_reg[56] :
              Delay3_bypass[56]);
  assign delayTapWire[58] = (ENA == 1'b1 ? Delay3_reg[57] :
              Delay3_bypass[57]);
  assign delayTapWire[59] = (ENA == 1'b1 ? Delay3_reg[58] :
              Delay3_bypass[58]);
  assign delayTapWire[60] = (ENA == 1'b1 ? Delay3_reg[59] :
              Delay3_bypass[59]);
  assign delayTapWire[61] = (ENA == 1'b1 ? Delay3_reg[60] :
              Delay3_bypass[60]);
  assign delayTapWire[62] = (ENA == 1'b1 ? Delay3_reg[61] :
              Delay3_bypass[61]);
  assign delayTapWire[63] = (ENA == 1'b1 ? Delay3_reg[62] :
              Delay3_bypass[62]);
  assign delayTapWire[64] = (ENA == 1'b1 ? Delay3_reg[63] :
              Delay3_bypass[63]);
  assign delayTapWire[65] = (ENA == 1'b1 ? Delay3_reg[64] :
              Delay3_bypass[64]);
  assign delayTapWire[66] = (ENA == 1'b1 ? Delay3_reg[65] :
              Delay3_bypass[65]);
  assign delayTapWire[67] = (ENA == 1'b1 ? Delay3_reg[66] :
              Delay3_bypass[66]);
  assign delayTapWire[68] = (ENA == 1'b1 ? Delay3_reg[67] :
              Delay3_bypass[67]);
  assign delayTapWire[69] = (ENA == 1'b1 ? Delay3_reg[68] :
              Delay3_bypass[68]);
  assign delayTapWire[70] = (ENA == 1'b1 ? Delay3_reg[69] :
              Delay3_bypass[69]);
  assign delayTapWire[71] = (ENA == 1'b1 ? Delay3_reg[70] :
              Delay3_bypass[70]);
  assign delayTapWire[72] = (ENA == 1'b1 ? Delay3_reg[71] :
              Delay3_bypass[71]);
  assign delayTapWire[73] = (ENA == 1'b1 ? Delay3_reg[72] :
              Delay3_bypass[72]);
  assign delayTapWire[74] = (ENA == 1'b1 ? Delay3_reg[73] :
              Delay3_bypass[73]);
  assign delayTapWire[75] = (ENA == 1'b1 ? Delay3_reg[74] :
              Delay3_bypass[74]);
  assign delayTapWire[76] = (ENA == 1'b1 ? Delay3_reg[75] :
              Delay3_bypass[75]);
  assign delayTapWire[77] = (ENA == 1'b1 ? Delay3_reg[76] :
              Delay3_bypass[76]);
  assign delayTapWire[78] = (ENA == 1'b1 ? Delay3_reg[77] :
              Delay3_bypass[77]);
  assign delayTapWire[79] = (ENA == 1'b1 ? Delay3_reg[78] :
              Delay3_bypass[78]);
  assign delayTapWire[80] = (ENA == 1'b1 ? Delay3_reg[79] :
              Delay3_bypass[79]);
  assign delayTapWire[81] = (ENA == 1'b1 ? Delay3_reg[80] :
              Delay3_bypass[80]);
  assign delayTapWire[82] = (ENA == 1'b1 ? Delay3_reg[81] :
              Delay3_bypass[81]);
  assign delayTapWire[83] = (ENA == 1'b1 ? Delay3_reg[82] :
              Delay3_bypass[82]);
  assign delayTapWire[84] = (ENA == 1'b1 ? Delay3_reg[83] :
              Delay3_bypass[83]);
  assign delayTapWire[85] = (ENA == 1'b1 ? Delay3_reg[84] :
              Delay3_bypass[84]);
  assign delayTapWire[86] = (ENA == 1'b1 ? Delay3_reg[85] :
              Delay3_bypass[85]);
  assign delayTapWire[87] = (ENA == 1'b1 ? Delay3_reg[86] :
              Delay3_bypass[86]);
  assign delayTapWire[88] = (ENA == 1'b1 ? Delay3_reg[87] :
              Delay3_bypass[87]);
  assign delayTapWire[89] = (ENA == 1'b1 ? Delay3_reg[88] :
              Delay3_bypass[88]);
  assign delayTapWire[90] = (ENA == 1'b1 ? Delay3_reg[89] :
              Delay3_bypass[89]);
  assign delayTapWire[91] = (ENA == 1'b1 ? Delay3_reg[90] :
              Delay3_bypass[90]);
  assign delayTapWire[92] = (ENA == 1'b1 ? Delay3_reg[91] :
              Delay3_bypass[91]);
  assign delayTapWire[93] = (ENA == 1'b1 ? Delay3_reg[92] :
              Delay3_bypass[92]);
  assign delayTapWire[94] = (ENA == 1'b1 ? Delay3_reg[93] :
              Delay3_bypass[93]);
  assign delayTapWire[95] = (ENA == 1'b1 ? Delay3_reg[94] :
              Delay3_bypass[94]);
  assign delayTapWire[96] = (ENA == 1'b1 ? Delay3_reg[95] :
              Delay3_bypass[95]);
  assign delayTapWire[97] = (ENA == 1'b1 ? Delay3_reg[96] :
              Delay3_bypass[96]);
  assign delayTapWire[98] = (ENA == 1'b1 ? Delay3_reg[97] :
              Delay3_bypass[97]);
  assign delayTapWire[99] = (ENA == 1'b1 ? Delay3_reg[98] :
              Delay3_bypass[98]);
  assign delayTapWire[100] = (ENA == 1'b1 ? Delay3_reg[99] :
              Delay3_bypass[99]);
  assign delayTapWire[101] = (ENA == 1'b1 ? Delay3_reg[100] :
              Delay3_bypass[100]);
  assign delayTapWire[102] = (ENA == 1'b1 ? Delay3_reg[101] :
              Delay3_bypass[101]);
  assign delayTapWire[103] = (ENA == 1'b1 ? Delay3_reg[102] :
              Delay3_bypass[102]);
  assign delayTapWire[104] = (ENA == 1'b1 ? Delay3_reg[103] :
              Delay3_bypass[103]);
  assign delayTapWire[105] = (ENA == 1'b1 ? Delay3_reg[104] :
              Delay3_bypass[104]);
  assign delayTapWire[106] = (ENA == 1'b1 ? Delay3_reg[105] :
              Delay3_bypass[105]);
  assign delayTapWire[107] = (ENA == 1'b1 ? Delay3_reg[106] :
              Delay3_bypass[106]);
  assign delayTapWire[108] = (ENA == 1'b1 ? Delay3_reg[107] :
              Delay3_bypass[107]);
  assign delayTapWire[109] = (ENA == 1'b1 ? Delay3_reg[108] :
              Delay3_bypass[108]);
  assign delayTapWire[110] = (ENA == 1'b1 ? Delay3_reg[109] :
              Delay3_bypass[109]);
  assign delayTapWire[111] = (ENA == 1'b1 ? Delay3_reg[110] :
              Delay3_bypass[110]);
  assign delayTapWire[112] = (ENA == 1'b1 ? Delay3_reg[111] :
              Delay3_bypass[111]);
  assign delayTapWire[113] = (ENA == 1'b1 ? Delay3_reg[112] :
              Delay3_bypass[112]);
  assign delayTapWire[114] = (ENA == 1'b1 ? Delay3_reg[113] :
              Delay3_bypass[113]);
  assign delayTapWire[115] = (ENA == 1'b1 ? Delay3_reg[114] :
              Delay3_bypass[114]);
  assign delayTapWire[116] = (ENA == 1'b1 ? Delay3_reg[115] :
              Delay3_bypass[115]);
  assign delayTapWire[117] = (ENA == 1'b1 ? Delay3_reg[116] :
              Delay3_bypass[116]);
  assign delayTapWire[118] = (ENA == 1'b1 ? Delay3_reg[117] :
              Delay3_bypass[117]);
  assign delayTapWire[119] = (ENA == 1'b1 ? Delay3_reg[118] :
              Delay3_bypass[118]);
  assign delayTapWire[120] = (ENA == 1'b1 ? Delay3_reg[119] :
              Delay3_bypass[119]);
  assign delayTapWire[121] = (ENA == 1'b1 ? Delay3_reg[120] :
              Delay3_bypass[120]);
  assign delayTapWire[122] = (ENA == 1'b1 ? Delay3_reg[121] :
              Delay3_bypass[121]);
  assign delayTapWire[123] = (ENA == 1'b1 ? Delay3_reg[122] :
              Delay3_bypass[122]);
  assign delayTapWire[124] = (ENA == 1'b1 ? Delay3_reg[123] :
              Delay3_bypass[123]);
  assign delayTapWire[125] = (ENA == 1'b1 ? Delay3_reg[124] :
              Delay3_bypass[124]);
  assign delayTapWire[126] = (ENA == 1'b1 ? Delay3_reg[125] :
              Delay3_bypass[125]);
  assign delayTapWire[127] = (ENA == 1'b1 ? Delay3_reg[126] :
              Delay3_bypass[126]);
  assign delayTapWire[128] = (ENA == 1'b1 ? Delay3_reg[127] :
              Delay3_bypass[127]);
  assign Delay3_bypass_next[0] = Delay3_reg[0];
  assign Delay3_bypass_next[1] = Delay3_reg[1];
  assign Delay3_bypass_next[2] = Delay3_reg[2];
  assign Delay3_bypass_next[3] = Delay3_reg[3];
  assign Delay3_bypass_next[4] = Delay3_reg[4];
  assign Delay3_bypass_next[5] = Delay3_reg[5];
  assign Delay3_bypass_next[6] = Delay3_reg[6];
  assign Delay3_bypass_next[7] = Delay3_reg[7];
  assign Delay3_bypass_next[8] = Delay3_reg[8];
  assign Delay3_bypass_next[9] = Delay3_reg[9];
  assign Delay3_bypass_next[10] = Delay3_reg[10];
  assign Delay3_bypass_next[11] = Delay3_reg[11];
  assign Delay3_bypass_next[12] = Delay3_reg[12];
  assign Delay3_bypass_next[13] = Delay3_reg[13];
  assign Delay3_bypass_next[14] = Delay3_reg[14];
  assign Delay3_bypass_next[15] = Delay3_reg[15];
  assign Delay3_bypass_next[16] = Delay3_reg[16];
  assign Delay3_bypass_next[17] = Delay3_reg[17];
  assign Delay3_bypass_next[18] = Delay3_reg[18];
  assign Delay3_bypass_next[19] = Delay3_reg[19];
  assign Delay3_bypass_next[20] = Delay3_reg[20];
  assign Delay3_bypass_next[21] = Delay3_reg[21];
  assign Delay3_bypass_next[22] = Delay3_reg[22];
  assign Delay3_bypass_next[23] = Delay3_reg[23];
  assign Delay3_bypass_next[24] = Delay3_reg[24];
  assign Delay3_bypass_next[25] = Delay3_reg[25];
  assign Delay3_bypass_next[26] = Delay3_reg[26];
  assign Delay3_bypass_next[27] = Delay3_reg[27];
  assign Delay3_bypass_next[28] = Delay3_reg[28];
  assign Delay3_bypass_next[29] = Delay3_reg[29];
  assign Delay3_bypass_next[30] = Delay3_reg[30];
  assign Delay3_bypass_next[31] = Delay3_reg[31];
  assign Delay3_bypass_next[32] = Delay3_reg[32];
  assign Delay3_bypass_next[33] = Delay3_reg[33];
  assign Delay3_bypass_next[34] = Delay3_reg[34];
  assign Delay3_bypass_next[35] = Delay3_reg[35];
  assign Delay3_bypass_next[36] = Delay3_reg[36];
  assign Delay3_bypass_next[37] = Delay3_reg[37];
  assign Delay3_bypass_next[38] = Delay3_reg[38];
  assign Delay3_bypass_next[39] = Delay3_reg[39];
  assign Delay3_bypass_next[40] = Delay3_reg[40];
  assign Delay3_bypass_next[41] = Delay3_reg[41];
  assign Delay3_bypass_next[42] = Delay3_reg[42];
  assign Delay3_bypass_next[43] = Delay3_reg[43];
  assign Delay3_bypass_next[44] = Delay3_reg[44];
  assign Delay3_bypass_next[45] = Delay3_reg[45];
  assign Delay3_bypass_next[46] = Delay3_reg[46];
  assign Delay3_bypass_next[47] = Delay3_reg[47];
  assign Delay3_bypass_next[48] = Delay3_reg[48];
  assign Delay3_bypass_next[49] = Delay3_reg[49];
  assign Delay3_bypass_next[50] = Delay3_reg[50];
  assign Delay3_bypass_next[51] = Delay3_reg[51];
  assign Delay3_bypass_next[52] = Delay3_reg[52];
  assign Delay3_bypass_next[53] = Delay3_reg[53];
  assign Delay3_bypass_next[54] = Delay3_reg[54];
  assign Delay3_bypass_next[55] = Delay3_reg[55];
  assign Delay3_bypass_next[56] = Delay3_reg[56];
  assign Delay3_bypass_next[57] = Delay3_reg[57];
  assign Delay3_bypass_next[58] = Delay3_reg[58];
  assign Delay3_bypass_next[59] = Delay3_reg[59];
  assign Delay3_bypass_next[60] = Delay3_reg[60];
  assign Delay3_bypass_next[61] = Delay3_reg[61];
  assign Delay3_bypass_next[62] = Delay3_reg[62];
  assign Delay3_bypass_next[63] = Delay3_reg[63];
  assign Delay3_bypass_next[64] = Delay3_reg[64];
  assign Delay3_bypass_next[65] = Delay3_reg[65];
  assign Delay3_bypass_next[66] = Delay3_reg[66];
  assign Delay3_bypass_next[67] = Delay3_reg[67];
  assign Delay3_bypass_next[68] = Delay3_reg[68];
  assign Delay3_bypass_next[69] = Delay3_reg[69];
  assign Delay3_bypass_next[70] = Delay3_reg[70];
  assign Delay3_bypass_next[71] = Delay3_reg[71];
  assign Delay3_bypass_next[72] = Delay3_reg[72];
  assign Delay3_bypass_next[73] = Delay3_reg[73];
  assign Delay3_bypass_next[74] = Delay3_reg[74];
  assign Delay3_bypass_next[75] = Delay3_reg[75];
  assign Delay3_bypass_next[76] = Delay3_reg[76];
  assign Delay3_bypass_next[77] = Delay3_reg[77];
  assign Delay3_bypass_next[78] = Delay3_reg[78];
  assign Delay3_bypass_next[79] = Delay3_reg[79];
  assign Delay3_bypass_next[80] = Delay3_reg[80];
  assign Delay3_bypass_next[81] = Delay3_reg[81];
  assign Delay3_bypass_next[82] = Delay3_reg[82];
  assign Delay3_bypass_next[83] = Delay3_reg[83];
  assign Delay3_bypass_next[84] = Delay3_reg[84];
  assign Delay3_bypass_next[85] = Delay3_reg[85];
  assign Delay3_bypass_next[86] = Delay3_reg[86];
  assign Delay3_bypass_next[87] = Delay3_reg[87];
  assign Delay3_bypass_next[88] = Delay3_reg[88];
  assign Delay3_bypass_next[89] = Delay3_reg[89];
  assign Delay3_bypass_next[90] = Delay3_reg[90];
  assign Delay3_bypass_next[91] = Delay3_reg[91];
  assign Delay3_bypass_next[92] = Delay3_reg[92];
  assign Delay3_bypass_next[93] = Delay3_reg[93];
  assign Delay3_bypass_next[94] = Delay3_reg[94];
  assign Delay3_bypass_next[95] = Delay3_reg[95];
  assign Delay3_bypass_next[96] = Delay3_reg[96];
  assign Delay3_bypass_next[97] = Delay3_reg[97];
  assign Delay3_bypass_next[98] = Delay3_reg[98];
  assign Delay3_bypass_next[99] = Delay3_reg[99];
  assign Delay3_bypass_next[100] = Delay3_reg[100];
  assign Delay3_bypass_next[101] = Delay3_reg[101];
  assign Delay3_bypass_next[102] = Delay3_reg[102];
  assign Delay3_bypass_next[103] = Delay3_reg[103];
  assign Delay3_bypass_next[104] = Delay3_reg[104];
  assign Delay3_bypass_next[105] = Delay3_reg[105];
  assign Delay3_bypass_next[106] = Delay3_reg[106];
  assign Delay3_bypass_next[107] = Delay3_reg[107];
  assign Delay3_bypass_next[108] = Delay3_reg[108];
  assign Delay3_bypass_next[109] = Delay3_reg[109];
  assign Delay3_bypass_next[110] = Delay3_reg[110];
  assign Delay3_bypass_next[111] = Delay3_reg[111];
  assign Delay3_bypass_next[112] = Delay3_reg[112];
  assign Delay3_bypass_next[113] = Delay3_reg[113];
  assign Delay3_bypass_next[114] = Delay3_reg[114];
  assign Delay3_bypass_next[115] = Delay3_reg[115];
  assign Delay3_bypass_next[116] = Delay3_reg[116];
  assign Delay3_bypass_next[117] = Delay3_reg[117];
  assign Delay3_bypass_next[118] = Delay3_reg[118];
  assign Delay3_bypass_next[119] = Delay3_reg[119];
  assign Delay3_bypass_next[120] = Delay3_reg[120];
  assign Delay3_bypass_next[121] = Delay3_reg[121];
  assign Delay3_bypass_next[122] = Delay3_reg[122];
  assign Delay3_bypass_next[123] = Delay3_reg[123];
  assign Delay3_bypass_next[124] = Delay3_reg[124];
  assign Delay3_bypass_next[125] = Delay3_reg[125];
  assign Delay3_bypass_next[126] = Delay3_reg[126];
  assign Delay3_bypass_next[127] = Delay3_reg[127];
  assign Delay3_reg_next[0] = DATA_DELAY;
  assign Delay3_reg_next[1] = Delay3_reg[0];
  assign Delay3_reg_next[2] = Delay3_reg[1];
  assign Delay3_reg_next[3] = Delay3_reg[2];
  assign Delay3_reg_next[4] = Delay3_reg[3];
  assign Delay3_reg_next[5] = Delay3_reg[4];
  assign Delay3_reg_next[6] = Delay3_reg[5];
  assign Delay3_reg_next[7] = Delay3_reg[6];
  assign Delay3_reg_next[8] = Delay3_reg[7];
  assign Delay3_reg_next[9] = Delay3_reg[8];
  assign Delay3_reg_next[10] = Delay3_reg[9];
  assign Delay3_reg_next[11] = Delay3_reg[10];
  assign Delay3_reg_next[12] = Delay3_reg[11];
  assign Delay3_reg_next[13] = Delay3_reg[12];
  assign Delay3_reg_next[14] = Delay3_reg[13];
  assign Delay3_reg_next[15] = Delay3_reg[14];
  assign Delay3_reg_next[16] = Delay3_reg[15];
  assign Delay3_reg_next[17] = Delay3_reg[16];
  assign Delay3_reg_next[18] = Delay3_reg[17];
  assign Delay3_reg_next[19] = Delay3_reg[18];
  assign Delay3_reg_next[20] = Delay3_reg[19];
  assign Delay3_reg_next[21] = Delay3_reg[20];
  assign Delay3_reg_next[22] = Delay3_reg[21];
  assign Delay3_reg_next[23] = Delay3_reg[22];
  assign Delay3_reg_next[24] = Delay3_reg[23];
  assign Delay3_reg_next[25] = Delay3_reg[24];
  assign Delay3_reg_next[26] = Delay3_reg[25];
  assign Delay3_reg_next[27] = Delay3_reg[26];
  assign Delay3_reg_next[28] = Delay3_reg[27];
  assign Delay3_reg_next[29] = Delay3_reg[28];
  assign Delay3_reg_next[30] = Delay3_reg[29];
  assign Delay3_reg_next[31] = Delay3_reg[30];
  assign Delay3_reg_next[32] = Delay3_reg[31];
  assign Delay3_reg_next[33] = Delay3_reg[32];
  assign Delay3_reg_next[34] = Delay3_reg[33];
  assign Delay3_reg_next[35] = Delay3_reg[34];
  assign Delay3_reg_next[36] = Delay3_reg[35];
  assign Delay3_reg_next[37] = Delay3_reg[36];
  assign Delay3_reg_next[38] = Delay3_reg[37];
  assign Delay3_reg_next[39] = Delay3_reg[38];
  assign Delay3_reg_next[40] = Delay3_reg[39];
  assign Delay3_reg_next[41] = Delay3_reg[40];
  assign Delay3_reg_next[42] = Delay3_reg[41];
  assign Delay3_reg_next[43] = Delay3_reg[42];
  assign Delay3_reg_next[44] = Delay3_reg[43];
  assign Delay3_reg_next[45] = Delay3_reg[44];
  assign Delay3_reg_next[46] = Delay3_reg[45];
  assign Delay3_reg_next[47] = Delay3_reg[46];
  assign Delay3_reg_next[48] = Delay3_reg[47];
  assign Delay3_reg_next[49] = Delay3_reg[48];
  assign Delay3_reg_next[50] = Delay3_reg[49];
  assign Delay3_reg_next[51] = Delay3_reg[50];
  assign Delay3_reg_next[52] = Delay3_reg[51];
  assign Delay3_reg_next[53] = Delay3_reg[52];
  assign Delay3_reg_next[54] = Delay3_reg[53];
  assign Delay3_reg_next[55] = Delay3_reg[54];
  assign Delay3_reg_next[56] = Delay3_reg[55];
  assign Delay3_reg_next[57] = Delay3_reg[56];
  assign Delay3_reg_next[58] = Delay3_reg[57];
  assign Delay3_reg_next[59] = Delay3_reg[58];
  assign Delay3_reg_next[60] = Delay3_reg[59];
  assign Delay3_reg_next[61] = Delay3_reg[60];
  assign Delay3_reg_next[62] = Delay3_reg[61];
  assign Delay3_reg_next[63] = Delay3_reg[62];
  assign Delay3_reg_next[64] = Delay3_reg[63];
  assign Delay3_reg_next[65] = Delay3_reg[64];
  assign Delay3_reg_next[66] = Delay3_reg[65];
  assign Delay3_reg_next[67] = Delay3_reg[66];
  assign Delay3_reg_next[68] = Delay3_reg[67];
  assign Delay3_reg_next[69] = Delay3_reg[68];
  assign Delay3_reg_next[70] = Delay3_reg[69];
  assign Delay3_reg_next[71] = Delay3_reg[70];
  assign Delay3_reg_next[72] = Delay3_reg[71];
  assign Delay3_reg_next[73] = Delay3_reg[72];
  assign Delay3_reg_next[74] = Delay3_reg[73];
  assign Delay3_reg_next[75] = Delay3_reg[74];
  assign Delay3_reg_next[76] = Delay3_reg[75];
  assign Delay3_reg_next[77] = Delay3_reg[76];
  assign Delay3_reg_next[78] = Delay3_reg[77];
  assign Delay3_reg_next[79] = Delay3_reg[78];
  assign Delay3_reg_next[80] = Delay3_reg[79];
  assign Delay3_reg_next[81] = Delay3_reg[80];
  assign Delay3_reg_next[82] = Delay3_reg[81];
  assign Delay3_reg_next[83] = Delay3_reg[82];
  assign Delay3_reg_next[84] = Delay3_reg[83];
  assign Delay3_reg_next[85] = Delay3_reg[84];
  assign Delay3_reg_next[86] = Delay3_reg[85];
  assign Delay3_reg_next[87] = Delay3_reg[86];
  assign Delay3_reg_next[88] = Delay3_reg[87];
  assign Delay3_reg_next[89] = Delay3_reg[88];
  assign Delay3_reg_next[90] = Delay3_reg[89];
  assign Delay3_reg_next[91] = Delay3_reg[90];
  assign Delay3_reg_next[92] = Delay3_reg[91];
  assign Delay3_reg_next[93] = Delay3_reg[92];
  assign Delay3_reg_next[94] = Delay3_reg[93];
  assign Delay3_reg_next[95] = Delay3_reg[94];
  assign Delay3_reg_next[96] = Delay3_reg[95];
  assign Delay3_reg_next[97] = Delay3_reg[96];
  assign Delay3_reg_next[98] = Delay3_reg[97];
  assign Delay3_reg_next[99] = Delay3_reg[98];
  assign Delay3_reg_next[100] = Delay3_reg[99];
  assign Delay3_reg_next[101] = Delay3_reg[100];
  assign Delay3_reg_next[102] = Delay3_reg[101];
  assign Delay3_reg_next[103] = Delay3_reg[102];
  assign Delay3_reg_next[104] = Delay3_reg[103];
  assign Delay3_reg_next[105] = Delay3_reg[104];
  assign Delay3_reg_next[106] = Delay3_reg[105];
  assign Delay3_reg_next[107] = Delay3_reg[106];
  assign Delay3_reg_next[108] = Delay3_reg[107];
  assign Delay3_reg_next[109] = Delay3_reg[108];
  assign Delay3_reg_next[110] = Delay3_reg[109];
  assign Delay3_reg_next[111] = Delay3_reg[110];
  assign Delay3_reg_next[112] = Delay3_reg[111];
  assign Delay3_reg_next[113] = Delay3_reg[112];
  assign Delay3_reg_next[114] = Delay3_reg[113];
  assign Delay3_reg_next[115] = Delay3_reg[114];
  assign Delay3_reg_next[116] = Delay3_reg[115];
  assign Delay3_reg_next[117] = Delay3_reg[116];
  assign Delay3_reg_next[118] = Delay3_reg[117];
  assign Delay3_reg_next[119] = Delay3_reg[118];
  assign Delay3_reg_next[120] = Delay3_reg[119];
  assign Delay3_reg_next[121] = Delay3_reg[120];
  assign Delay3_reg_next[122] = Delay3_reg[121];
  assign Delay3_reg_next[123] = Delay3_reg[122];
  assign Delay3_reg_next[124] = Delay3_reg[123];
  assign Delay3_reg_next[125] = Delay3_reg[124];
  assign Delay3_reg_next[126] = Delay3_reg[125];
  assign Delay3_reg_next[127] = Delay3_reg[126];



  assign Delay3_out1 = (controlSigOut == 8'b00000000 ? delayTapWire[0] :
              (controlSigOut == 8'b00000001 ? delayTapWire[1] :
              (controlSigOut == 8'b00000010 ? delayTapWire[2] :
              (controlSigOut == 8'b00000011 ? delayTapWire[3] :
              (controlSigOut == 8'b00000100 ? delayTapWire[4] :
              (controlSigOut == 8'b00000101 ? delayTapWire[5] :
              (controlSigOut == 8'b00000110 ? delayTapWire[6] :
              (controlSigOut == 8'b00000111 ? delayTapWire[7] :
              (controlSigOut == 8'b00001000 ? delayTapWire[8] :
              (controlSigOut == 8'b00001001 ? delayTapWire[9] :
              (controlSigOut == 8'b00001010 ? delayTapWire[10] :
              (controlSigOut == 8'b00001011 ? delayTapWire[11] :
              (controlSigOut == 8'b00001100 ? delayTapWire[12] :
              (controlSigOut == 8'b00001101 ? delayTapWire[13] :
              (controlSigOut == 8'b00001110 ? delayTapWire[14] :
              (controlSigOut == 8'b00001111 ? delayTapWire[15] :
              (controlSigOut == 8'b00010000 ? delayTapWire[16] :
              (controlSigOut == 8'b00010001 ? delayTapWire[17] :
              (controlSigOut == 8'b00010010 ? delayTapWire[18] :
              (controlSigOut == 8'b00010011 ? delayTapWire[19] :
              (controlSigOut == 8'b00010100 ? delayTapWire[20] :
              (controlSigOut == 8'b00010101 ? delayTapWire[21] :
              (controlSigOut == 8'b00010110 ? delayTapWire[22] :
              (controlSigOut == 8'b00010111 ? delayTapWire[23] :
              (controlSigOut == 8'b00011000 ? delayTapWire[24] :
              (controlSigOut == 8'b00011001 ? delayTapWire[25] :
              (controlSigOut == 8'b00011010 ? delayTapWire[26] :
              (controlSigOut == 8'b00011011 ? delayTapWire[27] :
              (controlSigOut == 8'b00011100 ? delayTapWire[28] :
              (controlSigOut == 8'b00011101 ? delayTapWire[29] :
              (controlSigOut == 8'b00011110 ? delayTapWire[30] :
              (controlSigOut == 8'b00011111 ? delayTapWire[31] :
              (controlSigOut == 8'b00100000 ? delayTapWire[32] :
              (controlSigOut == 8'b00100001 ? delayTapWire[33] :
              (controlSigOut == 8'b00100010 ? delayTapWire[34] :
              (controlSigOut == 8'b00100011 ? delayTapWire[35] :
              (controlSigOut == 8'b00100100 ? delayTapWire[36] :
              (controlSigOut == 8'b00100101 ? delayTapWire[37] :
              (controlSigOut == 8'b00100110 ? delayTapWire[38] :
              (controlSigOut == 8'b00100111 ? delayTapWire[39] :
              (controlSigOut == 8'b00101000 ? delayTapWire[40] :
              (controlSigOut == 8'b00101001 ? delayTapWire[41] :
              (controlSigOut == 8'b00101010 ? delayTapWire[42] :
              (controlSigOut == 8'b00101011 ? delayTapWire[43] :
              (controlSigOut == 8'b00101100 ? delayTapWire[44] :
              (controlSigOut == 8'b00101101 ? delayTapWire[45] :
              (controlSigOut == 8'b00101110 ? delayTapWire[46] :
              (controlSigOut == 8'b00101111 ? delayTapWire[47] :
              (controlSigOut == 8'b00110000 ? delayTapWire[48] :
              (controlSigOut == 8'b00110001 ? delayTapWire[49] :
              (controlSigOut == 8'b00110010 ? delayTapWire[50] :
              (controlSigOut == 8'b00110011 ? delayTapWire[51] :
              (controlSigOut == 8'b00110100 ? delayTapWire[52] :
              (controlSigOut == 8'b00110101 ? delayTapWire[53] :
              (controlSigOut == 8'b00110110 ? delayTapWire[54] :
              (controlSigOut == 8'b00110111 ? delayTapWire[55] :
              (controlSigOut == 8'b00111000 ? delayTapWire[56] :
              (controlSigOut == 8'b00111001 ? delayTapWire[57] :
              (controlSigOut == 8'b00111010 ? delayTapWire[58] :
              (controlSigOut == 8'b00111011 ? delayTapWire[59] :
              (controlSigOut == 8'b00111100 ? delayTapWire[60] :
              (controlSigOut == 8'b00111101 ? delayTapWire[61] :
              (controlSigOut == 8'b00111110 ? delayTapWire[62] :
              (controlSigOut == 8'b00111111 ? delayTapWire[63] :
              (controlSigOut == 8'b01000000 ? delayTapWire[64] :
              (controlSigOut == 8'b01000001 ? delayTapWire[65] :
              (controlSigOut == 8'b01000010 ? delayTapWire[66] :
              (controlSigOut == 8'b01000011 ? delayTapWire[67] :
              (controlSigOut == 8'b01000100 ? delayTapWire[68] :
              (controlSigOut == 8'b01000101 ? delayTapWire[69] :
              (controlSigOut == 8'b01000110 ? delayTapWire[70] :
              (controlSigOut == 8'b01000111 ? delayTapWire[71] :
              (controlSigOut == 8'b01001000 ? delayTapWire[72] :
              (controlSigOut == 8'b01001001 ? delayTapWire[73] :
              (controlSigOut == 8'b01001010 ? delayTapWire[74] :
              (controlSigOut == 8'b01001011 ? delayTapWire[75] :
              (controlSigOut == 8'b01001100 ? delayTapWire[76] :
              (controlSigOut == 8'b01001101 ? delayTapWire[77] :
              (controlSigOut == 8'b01001110 ? delayTapWire[78] :
              (controlSigOut == 8'b01001111 ? delayTapWire[79] :
              (controlSigOut == 8'b01010000 ? delayTapWire[80] :
              (controlSigOut == 8'b01010001 ? delayTapWire[81] :
              (controlSigOut == 8'b01010010 ? delayTapWire[82] :
              (controlSigOut == 8'b01010011 ? delayTapWire[83] :
              (controlSigOut == 8'b01010100 ? delayTapWire[84] :
              (controlSigOut == 8'b01010101 ? delayTapWire[85] :
              (controlSigOut == 8'b01010110 ? delayTapWire[86] :
              (controlSigOut == 8'b01010111 ? delayTapWire[87] :
              (controlSigOut == 8'b01011000 ? delayTapWire[88] :
              (controlSigOut == 8'b01011001 ? delayTapWire[89] :
              (controlSigOut == 8'b01011010 ? delayTapWire[90] :
              (controlSigOut == 8'b01011011 ? delayTapWire[91] :
              (controlSigOut == 8'b01011100 ? delayTapWire[92] :
              (controlSigOut == 8'b01011101 ? delayTapWire[93] :
              (controlSigOut == 8'b01011110 ? delayTapWire[94] :
              (controlSigOut == 8'b01011111 ? delayTapWire[95] :
              (controlSigOut == 8'b01100000 ? delayTapWire[96] :
              (controlSigOut == 8'b01100001 ? delayTapWire[97] :
              (controlSigOut == 8'b01100010 ? delayTapWire[98] :
              (controlSigOut == 8'b01100011 ? delayTapWire[99] :
              (controlSigOut == 8'b01100100 ? delayTapWire[100] :
              (controlSigOut == 8'b01100101 ? delayTapWire[101] :
              (controlSigOut == 8'b01100110 ? delayTapWire[102] :
              (controlSigOut == 8'b01100111 ? delayTapWire[103] :
              (controlSigOut == 8'b01101000 ? delayTapWire[104] :
              (controlSigOut == 8'b01101001 ? delayTapWire[105] :
              (controlSigOut == 8'b01101010 ? delayTapWire[106] :
              (controlSigOut == 8'b01101011 ? delayTapWire[107] :
              (controlSigOut == 8'b01101100 ? delayTapWire[108] :
              (controlSigOut == 8'b01101101 ? delayTapWire[109] :
              (controlSigOut == 8'b01101110 ? delayTapWire[110] :
              (controlSigOut == 8'b01101111 ? delayTapWire[111] :
              (controlSigOut == 8'b01110000 ? delayTapWire[112] :
              (controlSigOut == 8'b01110001 ? delayTapWire[113] :
              (controlSigOut == 8'b01110010 ? delayTapWire[114] :
              (controlSigOut == 8'b01110011 ? delayTapWire[115] :
              (controlSigOut == 8'b01110100 ? delayTapWire[116] :
              (controlSigOut == 8'b01110101 ? delayTapWire[117] :
              (controlSigOut == 8'b01110110 ? delayTapWire[118] :
              (controlSigOut == 8'b01110111 ? delayTapWire[119] :
              (controlSigOut == 8'b01111000 ? delayTapWire[120] :
              (controlSigOut == 8'b01111001 ? delayTapWire[121] :
              (controlSigOut == 8'b01111010 ? delayTapWire[122] :
              (controlSigOut == 8'b01111011 ? delayTapWire[123] :
              (controlSigOut == 8'b01111100 ? delayTapWire[124] :
              (controlSigOut == 8'b01111101 ? delayTapWire[125] :
              (controlSigOut == 8'b01111110 ? delayTapWire[126] :
              (controlSigOut == 8'b01111111 ? delayTapWire[127] :
              delayTapWire[128]))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))));



  assign COUNT = Delay3_out1;

endmodule  // For_Each_Subsystem1

