// -------------------------------------------------------------
// 
// File Name: hdlsrc\fft_new\MATLAB_Bit_Slice.v
// Created: 2025-06-03 14:06:56
// 
// Generated by MATLAB 9.12 and HDL Coder 3.20
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: MATLAB_Bit_Slice
// Source Path: fft_new/Subsystem2/For Each Subsystem/MATLAB Bit Slice
// Hierarchy Level: 3
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module MATLAB_Bit_Slice
          (u,
           n,
           NFFT,
           y);


  input   [6:0] u;  // ufix7
  input   [7:0] n;  // uint8
  input   [7:0] NFFT;  // uint8
  output  y;  // ufix1


  reg  y_1;  // ufix1
  reg [7:0] bit_rsvd;  // uint8
  reg [7:0] bit_idx;  // uint8
  reg signed [8:0] sub_temp;  // sfix9
  reg signed [8:0] t_0;  // sfix9
  reg signed [8:0] t_1;  // sfix9


  always @(NFFT, n, u) begin
    bit_idx = 8'd0;
    t_0 = {1'b0, NFFT};
    t_1 = {1'b0, n};
    sub_temp = t_0 - t_1;
    if (sub_temp[8] == 1'b1) begin
      bit_rsvd = 8'b00000000;
    end
    else begin
      bit_rsvd = sub_temp[7:0];
    end
    if ((bit_rsvd >= 8'd1) && (bit_rsvd <= 8'd7)) begin
      bit_idx = bit_rsvd - 8'd1;
      y_1 = u[bit_idx];
    end
    else begin
      y_1 = 1'b0;
    end
  end



  assign y = y_1;

endmodule  // MATLAB_Bit_Slice

