// -------------------------------------------------------------
// 
// File Name: hdlsrc\fft_new\MATLAB_LOOT.v
// Created: 2025-06-03 14:06:56
// 
// Generated by MATLAB 9.12 and HDL Coder 3.20
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: MATLAB_LOOT
// Source Path: fft_new/Subsystem2/Subsystem/MATLAB LOOT
// Hierarchy Level: 3
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module MATLAB_LOOT
          (u_0,
           u_1,
           u_2,
           u_3,
           u_4,
           u_5,
           WFFT_fix_re_0,
           WFFT_fix_re_1,
           WFFT_fix_re_2,
           WFFT_fix_re_3,
           WFFT_fix_re_4,
           WFFT_fix_re_5,
           WFFT_fix_re_6,
           WFFT_fix_re_7,
           WFFT_fix_re_8,
           WFFT_fix_re_9,
           WFFT_fix_re_10,
           WFFT_fix_re_11,
           WFFT_fix_re_12,
           WFFT_fix_re_13,
           WFFT_fix_re_14,
           WFFT_fix_re_15,
           WFFT_fix_re_16,
           WFFT_fix_re_17,
           WFFT_fix_re_18,
           WFFT_fix_re_19,
           WFFT_fix_re_20,
           WFFT_fix_re_21,
           WFFT_fix_re_22,
           WFFT_fix_re_23,
           WFFT_fix_re_24,
           WFFT_fix_re_25,
           WFFT_fix_re_26,
           WFFT_fix_re_27,
           WFFT_fix_re_28,
           WFFT_fix_re_29,
           WFFT_fix_re_30,
           WFFT_fix_re_31,
           WFFT_fix_re_32,
           WFFT_fix_re_33,
           WFFT_fix_re_34,
           WFFT_fix_re_35,
           WFFT_fix_re_36,
           WFFT_fix_re_37,
           WFFT_fix_re_38,
           WFFT_fix_re_39,
           WFFT_fix_re_40,
           WFFT_fix_re_41,
           WFFT_fix_re_42,
           WFFT_fix_re_43,
           WFFT_fix_re_44,
           WFFT_fix_re_45,
           WFFT_fix_re_46,
           WFFT_fix_re_47,
           WFFT_fix_re_48,
           WFFT_fix_re_49,
           WFFT_fix_re_50,
           WFFT_fix_re_51,
           WFFT_fix_re_52,
           WFFT_fix_re_53,
           WFFT_fix_re_54,
           WFFT_fix_re_55,
           WFFT_fix_re_56,
           WFFT_fix_re_57,
           WFFT_fix_re_58,
           WFFT_fix_re_59,
           WFFT_fix_re_60,
           WFFT_fix_re_61,
           WFFT_fix_re_62,
           WFFT_fix_re_63,
           WFFT_fix_re_64,
           WFFT_fix_re_65,
           WFFT_fix_re_66,
           WFFT_fix_re_67,
           WFFT_fix_re_68,
           WFFT_fix_re_69,
           WFFT_fix_re_70,
           WFFT_fix_re_71,
           WFFT_fix_re_72,
           WFFT_fix_re_73,
           WFFT_fix_re_74,
           WFFT_fix_re_75,
           WFFT_fix_re_76,
           WFFT_fix_re_77,
           WFFT_fix_re_78,
           WFFT_fix_re_79,
           WFFT_fix_re_80,
           WFFT_fix_re_81,
           WFFT_fix_re_82,
           WFFT_fix_re_83,
           WFFT_fix_re_84,
           WFFT_fix_re_85,
           WFFT_fix_re_86,
           WFFT_fix_re_87,
           WFFT_fix_re_88,
           WFFT_fix_re_89,
           WFFT_fix_re_90,
           WFFT_fix_re_91,
           WFFT_fix_re_92,
           WFFT_fix_re_93,
           WFFT_fix_re_94,
           WFFT_fix_re_95,
           WFFT_fix_re_96,
           WFFT_fix_re_97,
           WFFT_fix_re_98,
           WFFT_fix_re_99,
           WFFT_fix_re_100,
           WFFT_fix_re_101,
           WFFT_fix_re_102,
           WFFT_fix_re_103,
           WFFT_fix_re_104,
           WFFT_fix_re_105,
           WFFT_fix_re_106,
           WFFT_fix_re_107,
           WFFT_fix_re_108,
           WFFT_fix_re_109,
           WFFT_fix_re_110,
           WFFT_fix_re_111,
           WFFT_fix_re_112,
           WFFT_fix_re_113,
           WFFT_fix_re_114,
           WFFT_fix_re_115,
           WFFT_fix_re_116,
           WFFT_fix_re_117,
           WFFT_fix_re_118,
           WFFT_fix_re_119,
           WFFT_fix_re_120,
           WFFT_fix_re_121,
           WFFT_fix_re_122,
           WFFT_fix_re_123,
           WFFT_fix_re_124,
           WFFT_fix_re_125,
           WFFT_fix_re_126,
           WFFT_fix_re_127,
           WFFT_fix_re_128,
           WFFT_fix_re_129,
           WFFT_fix_re_130,
           WFFT_fix_re_131,
           WFFT_fix_re_132,
           WFFT_fix_re_133,
           WFFT_fix_re_134,
           WFFT_fix_re_135,
           WFFT_fix_re_136,
           WFFT_fix_re_137,
           WFFT_fix_re_138,
           WFFT_fix_re_139,
           WFFT_fix_re_140,
           WFFT_fix_re_141,
           WFFT_fix_re_142,
           WFFT_fix_re_143,
           WFFT_fix_re_144,
           WFFT_fix_re_145,
           WFFT_fix_re_146,
           WFFT_fix_re_147,
           WFFT_fix_re_148,
           WFFT_fix_re_149,
           WFFT_fix_re_150,
           WFFT_fix_re_151,
           WFFT_fix_re_152,
           WFFT_fix_re_153,
           WFFT_fix_re_154,
           WFFT_fix_re_155,
           WFFT_fix_re_156,
           WFFT_fix_re_157,
           WFFT_fix_re_158,
           WFFT_fix_re_159,
           WFFT_fix_re_160,
           WFFT_fix_re_161,
           WFFT_fix_re_162,
           WFFT_fix_re_163,
           WFFT_fix_re_164,
           WFFT_fix_re_165,
           WFFT_fix_re_166,
           WFFT_fix_re_167,
           WFFT_fix_re_168,
           WFFT_fix_re_169,
           WFFT_fix_re_170,
           WFFT_fix_re_171,
           WFFT_fix_re_172,
           WFFT_fix_re_173,
           WFFT_fix_re_174,
           WFFT_fix_re_175,
           WFFT_fix_re_176,
           WFFT_fix_re_177,
           WFFT_fix_re_178,
           WFFT_fix_re_179,
           WFFT_fix_re_180,
           WFFT_fix_re_181,
           WFFT_fix_re_182,
           WFFT_fix_re_183,
           WFFT_fix_re_184,
           WFFT_fix_re_185,
           WFFT_fix_re_186,
           WFFT_fix_re_187,
           WFFT_fix_re_188,
           WFFT_fix_re_189,
           WFFT_fix_re_190,
           WFFT_fix_re_191,
           WFFT_fix_re_192,
           WFFT_fix_re_193,
           WFFT_fix_re_194,
           WFFT_fix_re_195,
           WFFT_fix_re_196,
           WFFT_fix_re_197,
           WFFT_fix_re_198,
           WFFT_fix_re_199,
           WFFT_fix_re_200,
           WFFT_fix_re_201,
           WFFT_fix_re_202,
           WFFT_fix_re_203,
           WFFT_fix_re_204,
           WFFT_fix_re_205,
           WFFT_fix_re_206,
           WFFT_fix_re_207,
           WFFT_fix_re_208,
           WFFT_fix_re_209,
           WFFT_fix_re_210,
           WFFT_fix_re_211,
           WFFT_fix_re_212,
           WFFT_fix_re_213,
           WFFT_fix_re_214,
           WFFT_fix_re_215,
           WFFT_fix_re_216,
           WFFT_fix_re_217,
           WFFT_fix_re_218,
           WFFT_fix_re_219,
           WFFT_fix_re_220,
           WFFT_fix_re_221,
           WFFT_fix_re_222,
           WFFT_fix_re_223,
           WFFT_fix_re_224,
           WFFT_fix_re_225,
           WFFT_fix_re_226,
           WFFT_fix_re_227,
           WFFT_fix_re_228,
           WFFT_fix_re_229,
           WFFT_fix_re_230,
           WFFT_fix_re_231,
           WFFT_fix_re_232,
           WFFT_fix_re_233,
           WFFT_fix_re_234,
           WFFT_fix_re_235,
           WFFT_fix_re_236,
           WFFT_fix_re_237,
           WFFT_fix_re_238,
           WFFT_fix_re_239,
           WFFT_fix_re_240,
           WFFT_fix_re_241,
           WFFT_fix_re_242,
           WFFT_fix_re_243,
           WFFT_fix_re_244,
           WFFT_fix_re_245,
           WFFT_fix_re_246,
           WFFT_fix_re_247,
           WFFT_fix_re_248,
           WFFT_fix_re_249,
           WFFT_fix_re_250,
           WFFT_fix_re_251,
           WFFT_fix_im_0,
           WFFT_fix_im_1,
           WFFT_fix_im_2,
           WFFT_fix_im_3,
           WFFT_fix_im_4,
           WFFT_fix_im_5,
           WFFT_fix_im_6,
           WFFT_fix_im_7,
           WFFT_fix_im_8,
           WFFT_fix_im_9,
           WFFT_fix_im_10,
           WFFT_fix_im_11,
           WFFT_fix_im_12,
           WFFT_fix_im_13,
           WFFT_fix_im_14,
           WFFT_fix_im_15,
           WFFT_fix_im_16,
           WFFT_fix_im_17,
           WFFT_fix_im_18,
           WFFT_fix_im_19,
           WFFT_fix_im_20,
           WFFT_fix_im_21,
           WFFT_fix_im_22,
           WFFT_fix_im_23,
           WFFT_fix_im_24,
           WFFT_fix_im_25,
           WFFT_fix_im_26,
           WFFT_fix_im_27,
           WFFT_fix_im_28,
           WFFT_fix_im_29,
           WFFT_fix_im_30,
           WFFT_fix_im_31,
           WFFT_fix_im_32,
           WFFT_fix_im_33,
           WFFT_fix_im_34,
           WFFT_fix_im_35,
           WFFT_fix_im_36,
           WFFT_fix_im_37,
           WFFT_fix_im_38,
           WFFT_fix_im_39,
           WFFT_fix_im_40,
           WFFT_fix_im_41,
           WFFT_fix_im_42,
           WFFT_fix_im_43,
           WFFT_fix_im_44,
           WFFT_fix_im_45,
           WFFT_fix_im_46,
           WFFT_fix_im_47,
           WFFT_fix_im_48,
           WFFT_fix_im_49,
           WFFT_fix_im_50,
           WFFT_fix_im_51,
           WFFT_fix_im_52,
           WFFT_fix_im_53,
           WFFT_fix_im_54,
           WFFT_fix_im_55,
           WFFT_fix_im_56,
           WFFT_fix_im_57,
           WFFT_fix_im_58,
           WFFT_fix_im_59,
           WFFT_fix_im_60,
           WFFT_fix_im_61,
           WFFT_fix_im_62,
           WFFT_fix_im_63,
           WFFT_fix_im_64,
           WFFT_fix_im_65,
           WFFT_fix_im_66,
           WFFT_fix_im_67,
           WFFT_fix_im_68,
           WFFT_fix_im_69,
           WFFT_fix_im_70,
           WFFT_fix_im_71,
           WFFT_fix_im_72,
           WFFT_fix_im_73,
           WFFT_fix_im_74,
           WFFT_fix_im_75,
           WFFT_fix_im_76,
           WFFT_fix_im_77,
           WFFT_fix_im_78,
           WFFT_fix_im_79,
           WFFT_fix_im_80,
           WFFT_fix_im_81,
           WFFT_fix_im_82,
           WFFT_fix_im_83,
           WFFT_fix_im_84,
           WFFT_fix_im_85,
           WFFT_fix_im_86,
           WFFT_fix_im_87,
           WFFT_fix_im_88,
           WFFT_fix_im_89,
           WFFT_fix_im_90,
           WFFT_fix_im_91,
           WFFT_fix_im_92,
           WFFT_fix_im_93,
           WFFT_fix_im_94,
           WFFT_fix_im_95,
           WFFT_fix_im_96,
           WFFT_fix_im_97,
           WFFT_fix_im_98,
           WFFT_fix_im_99,
           WFFT_fix_im_100,
           WFFT_fix_im_101,
           WFFT_fix_im_102,
           WFFT_fix_im_103,
           WFFT_fix_im_104,
           WFFT_fix_im_105,
           WFFT_fix_im_106,
           WFFT_fix_im_107,
           WFFT_fix_im_108,
           WFFT_fix_im_109,
           WFFT_fix_im_110,
           WFFT_fix_im_111,
           WFFT_fix_im_112,
           WFFT_fix_im_113,
           WFFT_fix_im_114,
           WFFT_fix_im_115,
           WFFT_fix_im_116,
           WFFT_fix_im_117,
           WFFT_fix_im_118,
           WFFT_fix_im_119,
           WFFT_fix_im_120,
           WFFT_fix_im_121,
           WFFT_fix_im_122,
           WFFT_fix_im_123,
           WFFT_fix_im_124,
           WFFT_fix_im_125,
           WFFT_fix_im_126,
           WFFT_fix_im_127,
           WFFT_fix_im_128,
           WFFT_fix_im_129,
           WFFT_fix_im_130,
           WFFT_fix_im_131,
           WFFT_fix_im_132,
           WFFT_fix_im_133,
           WFFT_fix_im_134,
           WFFT_fix_im_135,
           WFFT_fix_im_136,
           WFFT_fix_im_137,
           WFFT_fix_im_138,
           WFFT_fix_im_139,
           WFFT_fix_im_140,
           WFFT_fix_im_141,
           WFFT_fix_im_142,
           WFFT_fix_im_143,
           WFFT_fix_im_144,
           WFFT_fix_im_145,
           WFFT_fix_im_146,
           WFFT_fix_im_147,
           WFFT_fix_im_148,
           WFFT_fix_im_149,
           WFFT_fix_im_150,
           WFFT_fix_im_151,
           WFFT_fix_im_152,
           WFFT_fix_im_153,
           WFFT_fix_im_154,
           WFFT_fix_im_155,
           WFFT_fix_im_156,
           WFFT_fix_im_157,
           WFFT_fix_im_158,
           WFFT_fix_im_159,
           WFFT_fix_im_160,
           WFFT_fix_im_161,
           WFFT_fix_im_162,
           WFFT_fix_im_163,
           WFFT_fix_im_164,
           WFFT_fix_im_165,
           WFFT_fix_im_166,
           WFFT_fix_im_167,
           WFFT_fix_im_168,
           WFFT_fix_im_169,
           WFFT_fix_im_170,
           WFFT_fix_im_171,
           WFFT_fix_im_172,
           WFFT_fix_im_173,
           WFFT_fix_im_174,
           WFFT_fix_im_175,
           WFFT_fix_im_176,
           WFFT_fix_im_177,
           WFFT_fix_im_178,
           WFFT_fix_im_179,
           WFFT_fix_im_180,
           WFFT_fix_im_181,
           WFFT_fix_im_182,
           WFFT_fix_im_183,
           WFFT_fix_im_184,
           WFFT_fix_im_185,
           WFFT_fix_im_186,
           WFFT_fix_im_187,
           WFFT_fix_im_188,
           WFFT_fix_im_189,
           WFFT_fix_im_190,
           WFFT_fix_im_191,
           WFFT_fix_im_192,
           WFFT_fix_im_193,
           WFFT_fix_im_194,
           WFFT_fix_im_195,
           WFFT_fix_im_196,
           WFFT_fix_im_197,
           WFFT_fix_im_198,
           WFFT_fix_im_199,
           WFFT_fix_im_200,
           WFFT_fix_im_201,
           WFFT_fix_im_202,
           WFFT_fix_im_203,
           WFFT_fix_im_204,
           WFFT_fix_im_205,
           WFFT_fix_im_206,
           WFFT_fix_im_207,
           WFFT_fix_im_208,
           WFFT_fix_im_209,
           WFFT_fix_im_210,
           WFFT_fix_im_211,
           WFFT_fix_im_212,
           WFFT_fix_im_213,
           WFFT_fix_im_214,
           WFFT_fix_im_215,
           WFFT_fix_im_216,
           WFFT_fix_im_217,
           WFFT_fix_im_218,
           WFFT_fix_im_219,
           WFFT_fix_im_220,
           WFFT_fix_im_221,
           WFFT_fix_im_222,
           WFFT_fix_im_223,
           WFFT_fix_im_224,
           WFFT_fix_im_225,
           WFFT_fix_im_226,
           WFFT_fix_im_227,
           WFFT_fix_im_228,
           WFFT_fix_im_229,
           WFFT_fix_im_230,
           WFFT_fix_im_231,
           WFFT_fix_im_232,
           WFFT_fix_im_233,
           WFFT_fix_im_234,
           WFFT_fix_im_235,
           WFFT_fix_im_236,
           WFFT_fix_im_237,
           WFFT_fix_im_238,
           WFFT_fix_im_239,
           WFFT_fix_im_240,
           WFFT_fix_im_241,
           WFFT_fix_im_242,
           WFFT_fix_im_243,
           WFFT_fix_im_244,
           WFFT_fix_im_245,
           WFFT_fix_im_246,
           WFFT_fix_im_247,
           WFFT_fix_im_248,
           WFFT_fix_im_249,
           WFFT_fix_im_250,
           WFFT_fix_im_251,
           y_re_0,
           y_re_1,
           y_re_2,
           y_re_3,
           y_re_4,
           y_re_5,
           y_im_0,
           y_im_1,
           y_im_2,
           y_im_3,
           y_im_4,
           y_im_5);


  input   [8:0] u_0;  // ufix9
  input   [8:0] u_1;  // ufix9
  input   [8:0] u_2;  // ufix9
  input   [8:0] u_3;  // ufix9
  input   [8:0] u_4;  // ufix9
  input   [8:0] u_5;  // ufix9
  input   signed [15:0] WFFT_fix_re_0;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_1;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_2;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_3;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_4;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_5;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_6;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_7;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_8;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_9;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_10;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_11;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_12;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_13;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_14;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_15;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_16;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_17;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_18;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_19;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_20;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_21;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_22;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_23;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_24;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_25;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_26;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_27;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_28;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_29;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_30;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_31;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_32;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_33;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_34;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_35;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_36;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_37;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_38;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_39;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_40;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_41;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_42;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_43;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_44;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_45;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_46;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_47;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_48;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_49;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_50;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_51;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_52;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_53;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_54;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_55;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_56;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_57;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_58;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_59;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_60;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_61;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_62;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_63;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_64;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_65;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_66;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_67;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_68;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_69;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_70;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_71;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_72;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_73;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_74;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_75;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_76;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_77;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_78;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_79;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_80;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_81;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_82;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_83;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_84;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_85;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_86;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_87;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_88;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_89;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_90;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_91;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_92;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_93;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_94;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_95;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_96;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_97;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_98;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_99;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_100;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_101;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_102;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_103;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_104;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_105;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_106;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_107;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_108;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_109;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_110;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_111;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_112;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_113;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_114;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_115;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_116;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_117;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_118;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_119;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_120;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_121;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_122;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_123;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_124;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_125;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_126;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_127;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_128;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_129;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_130;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_131;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_132;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_133;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_134;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_135;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_136;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_137;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_138;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_139;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_140;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_141;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_142;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_143;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_144;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_145;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_146;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_147;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_148;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_149;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_150;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_151;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_152;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_153;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_154;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_155;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_156;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_157;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_158;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_159;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_160;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_161;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_162;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_163;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_164;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_165;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_166;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_167;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_168;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_169;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_170;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_171;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_172;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_173;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_174;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_175;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_176;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_177;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_178;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_179;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_180;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_181;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_182;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_183;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_184;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_185;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_186;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_187;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_188;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_189;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_190;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_191;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_192;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_193;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_194;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_195;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_196;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_197;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_198;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_199;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_200;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_201;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_202;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_203;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_204;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_205;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_206;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_207;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_208;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_209;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_210;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_211;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_212;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_213;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_214;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_215;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_216;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_217;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_218;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_219;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_220;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_221;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_222;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_223;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_224;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_225;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_226;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_227;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_228;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_229;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_230;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_231;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_232;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_233;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_234;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_235;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_236;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_237;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_238;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_239;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_240;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_241;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_242;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_243;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_244;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_245;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_246;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_247;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_248;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_249;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_250;  // sfix16_En14
  input   signed [15:0] WFFT_fix_re_251;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_0;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_1;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_2;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_3;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_4;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_5;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_6;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_7;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_8;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_9;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_10;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_11;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_12;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_13;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_14;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_15;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_16;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_17;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_18;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_19;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_20;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_21;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_22;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_23;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_24;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_25;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_26;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_27;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_28;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_29;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_30;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_31;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_32;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_33;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_34;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_35;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_36;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_37;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_38;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_39;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_40;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_41;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_42;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_43;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_44;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_45;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_46;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_47;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_48;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_49;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_50;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_51;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_52;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_53;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_54;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_55;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_56;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_57;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_58;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_59;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_60;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_61;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_62;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_63;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_64;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_65;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_66;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_67;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_68;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_69;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_70;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_71;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_72;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_73;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_74;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_75;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_76;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_77;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_78;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_79;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_80;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_81;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_82;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_83;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_84;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_85;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_86;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_87;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_88;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_89;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_90;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_91;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_92;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_93;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_94;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_95;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_96;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_97;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_98;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_99;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_100;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_101;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_102;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_103;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_104;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_105;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_106;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_107;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_108;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_109;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_110;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_111;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_112;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_113;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_114;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_115;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_116;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_117;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_118;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_119;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_120;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_121;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_122;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_123;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_124;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_125;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_126;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_127;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_128;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_129;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_130;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_131;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_132;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_133;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_134;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_135;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_136;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_137;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_138;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_139;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_140;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_141;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_142;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_143;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_144;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_145;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_146;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_147;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_148;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_149;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_150;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_151;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_152;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_153;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_154;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_155;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_156;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_157;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_158;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_159;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_160;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_161;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_162;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_163;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_164;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_165;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_166;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_167;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_168;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_169;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_170;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_171;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_172;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_173;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_174;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_175;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_176;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_177;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_178;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_179;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_180;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_181;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_182;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_183;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_184;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_185;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_186;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_187;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_188;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_189;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_190;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_191;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_192;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_193;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_194;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_195;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_196;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_197;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_198;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_199;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_200;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_201;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_202;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_203;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_204;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_205;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_206;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_207;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_208;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_209;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_210;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_211;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_212;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_213;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_214;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_215;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_216;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_217;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_218;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_219;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_220;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_221;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_222;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_223;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_224;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_225;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_226;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_227;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_228;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_229;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_230;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_231;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_232;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_233;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_234;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_235;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_236;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_237;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_238;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_239;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_240;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_241;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_242;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_243;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_244;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_245;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_246;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_247;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_248;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_249;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_250;  // sfix16_En14
  input   signed [15:0] WFFT_fix_im_251;  // sfix16_En14
  output  signed [15:0] y_re_0;  // sfix16_En14
  output  signed [15:0] y_re_1;  // sfix16_En14
  output  signed [15:0] y_re_2;  // sfix16_En14
  output  signed [15:0] y_re_3;  // sfix16_En14
  output  signed [15:0] y_re_4;  // sfix16_En14
  output  signed [15:0] y_re_5;  // sfix16_En14
  output  signed [15:0] y_im_0;  // sfix16_En14
  output  signed [15:0] y_im_1;  // sfix16_En14
  output  signed [15:0] y_im_2;  // sfix16_En14
  output  signed [15:0] y_im_3;  // sfix16_En14
  output  signed [15:0] y_im_4;  // sfix16_En14
  output  signed [15:0] y_im_5;  // sfix16_En14


  wire [8:0] u [0:5];  // ufix9 [6]
  wire signed [15:0] WFFT_fix_re [0:251];  // sfix16_En14 [252]
  wire signed [15:0] WFFT_fix_im [0:251];  // sfix16_En14 [252]
  wire signed [15:0] y_re [0:5];  // sfix16_En14 [6]
  wire signed [15:0] y_im [0:5];  // sfix16_En14 [6]
  wire [9:0] add_temp [0:5];  // ufix10 [6]
  wire [9:0] add_temp_1 [0:5];  // ufix10 [6]
  wire [9:0] s [0:5];  // ufix10 [6]
  wire [9:0] s_1 [0:5];  // ufix10 [6]


  assign u[0] = u_0;
  assign u[1] = u_1;
  assign u[2] = u_2;
  assign u[3] = u_3;
  assign u[4] = u_4;
  assign u[5] = u_5;

  assign WFFT_fix_re[0] = WFFT_fix_re_0;
  assign WFFT_fix_re[1] = WFFT_fix_re_1;
  assign WFFT_fix_re[2] = WFFT_fix_re_2;
  assign WFFT_fix_re[3] = WFFT_fix_re_3;
  assign WFFT_fix_re[4] = WFFT_fix_re_4;
  assign WFFT_fix_re[5] = WFFT_fix_re_5;
  assign WFFT_fix_re[6] = WFFT_fix_re_6;
  assign WFFT_fix_re[7] = WFFT_fix_re_7;
  assign WFFT_fix_re[8] = WFFT_fix_re_8;
  assign WFFT_fix_re[9] = WFFT_fix_re_9;
  assign WFFT_fix_re[10] = WFFT_fix_re_10;
  assign WFFT_fix_re[11] = WFFT_fix_re_11;
  assign WFFT_fix_re[12] = WFFT_fix_re_12;
  assign WFFT_fix_re[13] = WFFT_fix_re_13;
  assign WFFT_fix_re[14] = WFFT_fix_re_14;
  assign WFFT_fix_re[15] = WFFT_fix_re_15;
  assign WFFT_fix_re[16] = WFFT_fix_re_16;
  assign WFFT_fix_re[17] = WFFT_fix_re_17;
  assign WFFT_fix_re[18] = WFFT_fix_re_18;
  assign WFFT_fix_re[19] = WFFT_fix_re_19;
  assign WFFT_fix_re[20] = WFFT_fix_re_20;
  assign WFFT_fix_re[21] = WFFT_fix_re_21;
  assign WFFT_fix_re[22] = WFFT_fix_re_22;
  assign WFFT_fix_re[23] = WFFT_fix_re_23;
  assign WFFT_fix_re[24] = WFFT_fix_re_24;
  assign WFFT_fix_re[25] = WFFT_fix_re_25;
  assign WFFT_fix_re[26] = WFFT_fix_re_26;
  assign WFFT_fix_re[27] = WFFT_fix_re_27;
  assign WFFT_fix_re[28] = WFFT_fix_re_28;
  assign WFFT_fix_re[29] = WFFT_fix_re_29;
  assign WFFT_fix_re[30] = WFFT_fix_re_30;
  assign WFFT_fix_re[31] = WFFT_fix_re_31;
  assign WFFT_fix_re[32] = WFFT_fix_re_32;
  assign WFFT_fix_re[33] = WFFT_fix_re_33;
  assign WFFT_fix_re[34] = WFFT_fix_re_34;
  assign WFFT_fix_re[35] = WFFT_fix_re_35;
  assign WFFT_fix_re[36] = WFFT_fix_re_36;
  assign WFFT_fix_re[37] = WFFT_fix_re_37;
  assign WFFT_fix_re[38] = WFFT_fix_re_38;
  assign WFFT_fix_re[39] = WFFT_fix_re_39;
  assign WFFT_fix_re[40] = WFFT_fix_re_40;
  assign WFFT_fix_re[41] = WFFT_fix_re_41;
  assign WFFT_fix_re[42] = WFFT_fix_re_42;
  assign WFFT_fix_re[43] = WFFT_fix_re_43;
  assign WFFT_fix_re[44] = WFFT_fix_re_44;
  assign WFFT_fix_re[45] = WFFT_fix_re_45;
  assign WFFT_fix_re[46] = WFFT_fix_re_46;
  assign WFFT_fix_re[47] = WFFT_fix_re_47;
  assign WFFT_fix_re[48] = WFFT_fix_re_48;
  assign WFFT_fix_re[49] = WFFT_fix_re_49;
  assign WFFT_fix_re[50] = WFFT_fix_re_50;
  assign WFFT_fix_re[51] = WFFT_fix_re_51;
  assign WFFT_fix_re[52] = WFFT_fix_re_52;
  assign WFFT_fix_re[53] = WFFT_fix_re_53;
  assign WFFT_fix_re[54] = WFFT_fix_re_54;
  assign WFFT_fix_re[55] = WFFT_fix_re_55;
  assign WFFT_fix_re[56] = WFFT_fix_re_56;
  assign WFFT_fix_re[57] = WFFT_fix_re_57;
  assign WFFT_fix_re[58] = WFFT_fix_re_58;
  assign WFFT_fix_re[59] = WFFT_fix_re_59;
  assign WFFT_fix_re[60] = WFFT_fix_re_60;
  assign WFFT_fix_re[61] = WFFT_fix_re_61;
  assign WFFT_fix_re[62] = WFFT_fix_re_62;
  assign WFFT_fix_re[63] = WFFT_fix_re_63;
  assign WFFT_fix_re[64] = WFFT_fix_re_64;
  assign WFFT_fix_re[65] = WFFT_fix_re_65;
  assign WFFT_fix_re[66] = WFFT_fix_re_66;
  assign WFFT_fix_re[67] = WFFT_fix_re_67;
  assign WFFT_fix_re[68] = WFFT_fix_re_68;
  assign WFFT_fix_re[69] = WFFT_fix_re_69;
  assign WFFT_fix_re[70] = WFFT_fix_re_70;
  assign WFFT_fix_re[71] = WFFT_fix_re_71;
  assign WFFT_fix_re[72] = WFFT_fix_re_72;
  assign WFFT_fix_re[73] = WFFT_fix_re_73;
  assign WFFT_fix_re[74] = WFFT_fix_re_74;
  assign WFFT_fix_re[75] = WFFT_fix_re_75;
  assign WFFT_fix_re[76] = WFFT_fix_re_76;
  assign WFFT_fix_re[77] = WFFT_fix_re_77;
  assign WFFT_fix_re[78] = WFFT_fix_re_78;
  assign WFFT_fix_re[79] = WFFT_fix_re_79;
  assign WFFT_fix_re[80] = WFFT_fix_re_80;
  assign WFFT_fix_re[81] = WFFT_fix_re_81;
  assign WFFT_fix_re[82] = WFFT_fix_re_82;
  assign WFFT_fix_re[83] = WFFT_fix_re_83;
  assign WFFT_fix_re[84] = WFFT_fix_re_84;
  assign WFFT_fix_re[85] = WFFT_fix_re_85;
  assign WFFT_fix_re[86] = WFFT_fix_re_86;
  assign WFFT_fix_re[87] = WFFT_fix_re_87;
  assign WFFT_fix_re[88] = WFFT_fix_re_88;
  assign WFFT_fix_re[89] = WFFT_fix_re_89;
  assign WFFT_fix_re[90] = WFFT_fix_re_90;
  assign WFFT_fix_re[91] = WFFT_fix_re_91;
  assign WFFT_fix_re[92] = WFFT_fix_re_92;
  assign WFFT_fix_re[93] = WFFT_fix_re_93;
  assign WFFT_fix_re[94] = WFFT_fix_re_94;
  assign WFFT_fix_re[95] = WFFT_fix_re_95;
  assign WFFT_fix_re[96] = WFFT_fix_re_96;
  assign WFFT_fix_re[97] = WFFT_fix_re_97;
  assign WFFT_fix_re[98] = WFFT_fix_re_98;
  assign WFFT_fix_re[99] = WFFT_fix_re_99;
  assign WFFT_fix_re[100] = WFFT_fix_re_100;
  assign WFFT_fix_re[101] = WFFT_fix_re_101;
  assign WFFT_fix_re[102] = WFFT_fix_re_102;
  assign WFFT_fix_re[103] = WFFT_fix_re_103;
  assign WFFT_fix_re[104] = WFFT_fix_re_104;
  assign WFFT_fix_re[105] = WFFT_fix_re_105;
  assign WFFT_fix_re[106] = WFFT_fix_re_106;
  assign WFFT_fix_re[107] = WFFT_fix_re_107;
  assign WFFT_fix_re[108] = WFFT_fix_re_108;
  assign WFFT_fix_re[109] = WFFT_fix_re_109;
  assign WFFT_fix_re[110] = WFFT_fix_re_110;
  assign WFFT_fix_re[111] = WFFT_fix_re_111;
  assign WFFT_fix_re[112] = WFFT_fix_re_112;
  assign WFFT_fix_re[113] = WFFT_fix_re_113;
  assign WFFT_fix_re[114] = WFFT_fix_re_114;
  assign WFFT_fix_re[115] = WFFT_fix_re_115;
  assign WFFT_fix_re[116] = WFFT_fix_re_116;
  assign WFFT_fix_re[117] = WFFT_fix_re_117;
  assign WFFT_fix_re[118] = WFFT_fix_re_118;
  assign WFFT_fix_re[119] = WFFT_fix_re_119;
  assign WFFT_fix_re[120] = WFFT_fix_re_120;
  assign WFFT_fix_re[121] = WFFT_fix_re_121;
  assign WFFT_fix_re[122] = WFFT_fix_re_122;
  assign WFFT_fix_re[123] = WFFT_fix_re_123;
  assign WFFT_fix_re[124] = WFFT_fix_re_124;
  assign WFFT_fix_re[125] = WFFT_fix_re_125;
  assign WFFT_fix_re[126] = WFFT_fix_re_126;
  assign WFFT_fix_re[127] = WFFT_fix_re_127;
  assign WFFT_fix_re[128] = WFFT_fix_re_128;
  assign WFFT_fix_re[129] = WFFT_fix_re_129;
  assign WFFT_fix_re[130] = WFFT_fix_re_130;
  assign WFFT_fix_re[131] = WFFT_fix_re_131;
  assign WFFT_fix_re[132] = WFFT_fix_re_132;
  assign WFFT_fix_re[133] = WFFT_fix_re_133;
  assign WFFT_fix_re[134] = WFFT_fix_re_134;
  assign WFFT_fix_re[135] = WFFT_fix_re_135;
  assign WFFT_fix_re[136] = WFFT_fix_re_136;
  assign WFFT_fix_re[137] = WFFT_fix_re_137;
  assign WFFT_fix_re[138] = WFFT_fix_re_138;
  assign WFFT_fix_re[139] = WFFT_fix_re_139;
  assign WFFT_fix_re[140] = WFFT_fix_re_140;
  assign WFFT_fix_re[141] = WFFT_fix_re_141;
  assign WFFT_fix_re[142] = WFFT_fix_re_142;
  assign WFFT_fix_re[143] = WFFT_fix_re_143;
  assign WFFT_fix_re[144] = WFFT_fix_re_144;
  assign WFFT_fix_re[145] = WFFT_fix_re_145;
  assign WFFT_fix_re[146] = WFFT_fix_re_146;
  assign WFFT_fix_re[147] = WFFT_fix_re_147;
  assign WFFT_fix_re[148] = WFFT_fix_re_148;
  assign WFFT_fix_re[149] = WFFT_fix_re_149;
  assign WFFT_fix_re[150] = WFFT_fix_re_150;
  assign WFFT_fix_re[151] = WFFT_fix_re_151;
  assign WFFT_fix_re[152] = WFFT_fix_re_152;
  assign WFFT_fix_re[153] = WFFT_fix_re_153;
  assign WFFT_fix_re[154] = WFFT_fix_re_154;
  assign WFFT_fix_re[155] = WFFT_fix_re_155;
  assign WFFT_fix_re[156] = WFFT_fix_re_156;
  assign WFFT_fix_re[157] = WFFT_fix_re_157;
  assign WFFT_fix_re[158] = WFFT_fix_re_158;
  assign WFFT_fix_re[159] = WFFT_fix_re_159;
  assign WFFT_fix_re[160] = WFFT_fix_re_160;
  assign WFFT_fix_re[161] = WFFT_fix_re_161;
  assign WFFT_fix_re[162] = WFFT_fix_re_162;
  assign WFFT_fix_re[163] = WFFT_fix_re_163;
  assign WFFT_fix_re[164] = WFFT_fix_re_164;
  assign WFFT_fix_re[165] = WFFT_fix_re_165;
  assign WFFT_fix_re[166] = WFFT_fix_re_166;
  assign WFFT_fix_re[167] = WFFT_fix_re_167;
  assign WFFT_fix_re[168] = WFFT_fix_re_168;
  assign WFFT_fix_re[169] = WFFT_fix_re_169;
  assign WFFT_fix_re[170] = WFFT_fix_re_170;
  assign WFFT_fix_re[171] = WFFT_fix_re_171;
  assign WFFT_fix_re[172] = WFFT_fix_re_172;
  assign WFFT_fix_re[173] = WFFT_fix_re_173;
  assign WFFT_fix_re[174] = WFFT_fix_re_174;
  assign WFFT_fix_re[175] = WFFT_fix_re_175;
  assign WFFT_fix_re[176] = WFFT_fix_re_176;
  assign WFFT_fix_re[177] = WFFT_fix_re_177;
  assign WFFT_fix_re[178] = WFFT_fix_re_178;
  assign WFFT_fix_re[179] = WFFT_fix_re_179;
  assign WFFT_fix_re[180] = WFFT_fix_re_180;
  assign WFFT_fix_re[181] = WFFT_fix_re_181;
  assign WFFT_fix_re[182] = WFFT_fix_re_182;
  assign WFFT_fix_re[183] = WFFT_fix_re_183;
  assign WFFT_fix_re[184] = WFFT_fix_re_184;
  assign WFFT_fix_re[185] = WFFT_fix_re_185;
  assign WFFT_fix_re[186] = WFFT_fix_re_186;
  assign WFFT_fix_re[187] = WFFT_fix_re_187;
  assign WFFT_fix_re[188] = WFFT_fix_re_188;
  assign WFFT_fix_re[189] = WFFT_fix_re_189;
  assign WFFT_fix_re[190] = WFFT_fix_re_190;
  assign WFFT_fix_re[191] = WFFT_fix_re_191;
  assign WFFT_fix_re[192] = WFFT_fix_re_192;
  assign WFFT_fix_re[193] = WFFT_fix_re_193;
  assign WFFT_fix_re[194] = WFFT_fix_re_194;
  assign WFFT_fix_re[195] = WFFT_fix_re_195;
  assign WFFT_fix_re[196] = WFFT_fix_re_196;
  assign WFFT_fix_re[197] = WFFT_fix_re_197;
  assign WFFT_fix_re[198] = WFFT_fix_re_198;
  assign WFFT_fix_re[199] = WFFT_fix_re_199;
  assign WFFT_fix_re[200] = WFFT_fix_re_200;
  assign WFFT_fix_re[201] = WFFT_fix_re_201;
  assign WFFT_fix_re[202] = WFFT_fix_re_202;
  assign WFFT_fix_re[203] = WFFT_fix_re_203;
  assign WFFT_fix_re[204] = WFFT_fix_re_204;
  assign WFFT_fix_re[205] = WFFT_fix_re_205;
  assign WFFT_fix_re[206] = WFFT_fix_re_206;
  assign WFFT_fix_re[207] = WFFT_fix_re_207;
  assign WFFT_fix_re[208] = WFFT_fix_re_208;
  assign WFFT_fix_re[209] = WFFT_fix_re_209;
  assign WFFT_fix_re[210] = WFFT_fix_re_210;
  assign WFFT_fix_re[211] = WFFT_fix_re_211;
  assign WFFT_fix_re[212] = WFFT_fix_re_212;
  assign WFFT_fix_re[213] = WFFT_fix_re_213;
  assign WFFT_fix_re[214] = WFFT_fix_re_214;
  assign WFFT_fix_re[215] = WFFT_fix_re_215;
  assign WFFT_fix_re[216] = WFFT_fix_re_216;
  assign WFFT_fix_re[217] = WFFT_fix_re_217;
  assign WFFT_fix_re[218] = WFFT_fix_re_218;
  assign WFFT_fix_re[219] = WFFT_fix_re_219;
  assign WFFT_fix_re[220] = WFFT_fix_re_220;
  assign WFFT_fix_re[221] = WFFT_fix_re_221;
  assign WFFT_fix_re[222] = WFFT_fix_re_222;
  assign WFFT_fix_re[223] = WFFT_fix_re_223;
  assign WFFT_fix_re[224] = WFFT_fix_re_224;
  assign WFFT_fix_re[225] = WFFT_fix_re_225;
  assign WFFT_fix_re[226] = WFFT_fix_re_226;
  assign WFFT_fix_re[227] = WFFT_fix_re_227;
  assign WFFT_fix_re[228] = WFFT_fix_re_228;
  assign WFFT_fix_re[229] = WFFT_fix_re_229;
  assign WFFT_fix_re[230] = WFFT_fix_re_230;
  assign WFFT_fix_re[231] = WFFT_fix_re_231;
  assign WFFT_fix_re[232] = WFFT_fix_re_232;
  assign WFFT_fix_re[233] = WFFT_fix_re_233;
  assign WFFT_fix_re[234] = WFFT_fix_re_234;
  assign WFFT_fix_re[235] = WFFT_fix_re_235;
  assign WFFT_fix_re[236] = WFFT_fix_re_236;
  assign WFFT_fix_re[237] = WFFT_fix_re_237;
  assign WFFT_fix_re[238] = WFFT_fix_re_238;
  assign WFFT_fix_re[239] = WFFT_fix_re_239;
  assign WFFT_fix_re[240] = WFFT_fix_re_240;
  assign WFFT_fix_re[241] = WFFT_fix_re_241;
  assign WFFT_fix_re[242] = WFFT_fix_re_242;
  assign WFFT_fix_re[243] = WFFT_fix_re_243;
  assign WFFT_fix_re[244] = WFFT_fix_re_244;
  assign WFFT_fix_re[245] = WFFT_fix_re_245;
  assign WFFT_fix_re[246] = WFFT_fix_re_246;
  assign WFFT_fix_re[247] = WFFT_fix_re_247;
  assign WFFT_fix_re[248] = WFFT_fix_re_248;
  assign WFFT_fix_re[249] = WFFT_fix_re_249;
  assign WFFT_fix_re[250] = WFFT_fix_re_250;
  assign WFFT_fix_re[251] = WFFT_fix_re_251;

  assign WFFT_fix_im[0] = WFFT_fix_im_0;
  assign WFFT_fix_im[1] = WFFT_fix_im_1;
  assign WFFT_fix_im[2] = WFFT_fix_im_2;
  assign WFFT_fix_im[3] = WFFT_fix_im_3;
  assign WFFT_fix_im[4] = WFFT_fix_im_4;
  assign WFFT_fix_im[5] = WFFT_fix_im_5;
  assign WFFT_fix_im[6] = WFFT_fix_im_6;
  assign WFFT_fix_im[7] = WFFT_fix_im_7;
  assign WFFT_fix_im[8] = WFFT_fix_im_8;
  assign WFFT_fix_im[9] = WFFT_fix_im_9;
  assign WFFT_fix_im[10] = WFFT_fix_im_10;
  assign WFFT_fix_im[11] = WFFT_fix_im_11;
  assign WFFT_fix_im[12] = WFFT_fix_im_12;
  assign WFFT_fix_im[13] = WFFT_fix_im_13;
  assign WFFT_fix_im[14] = WFFT_fix_im_14;
  assign WFFT_fix_im[15] = WFFT_fix_im_15;
  assign WFFT_fix_im[16] = WFFT_fix_im_16;
  assign WFFT_fix_im[17] = WFFT_fix_im_17;
  assign WFFT_fix_im[18] = WFFT_fix_im_18;
  assign WFFT_fix_im[19] = WFFT_fix_im_19;
  assign WFFT_fix_im[20] = WFFT_fix_im_20;
  assign WFFT_fix_im[21] = WFFT_fix_im_21;
  assign WFFT_fix_im[22] = WFFT_fix_im_22;
  assign WFFT_fix_im[23] = WFFT_fix_im_23;
  assign WFFT_fix_im[24] = WFFT_fix_im_24;
  assign WFFT_fix_im[25] = WFFT_fix_im_25;
  assign WFFT_fix_im[26] = WFFT_fix_im_26;
  assign WFFT_fix_im[27] = WFFT_fix_im_27;
  assign WFFT_fix_im[28] = WFFT_fix_im_28;
  assign WFFT_fix_im[29] = WFFT_fix_im_29;
  assign WFFT_fix_im[30] = WFFT_fix_im_30;
  assign WFFT_fix_im[31] = WFFT_fix_im_31;
  assign WFFT_fix_im[32] = WFFT_fix_im_32;
  assign WFFT_fix_im[33] = WFFT_fix_im_33;
  assign WFFT_fix_im[34] = WFFT_fix_im_34;
  assign WFFT_fix_im[35] = WFFT_fix_im_35;
  assign WFFT_fix_im[36] = WFFT_fix_im_36;
  assign WFFT_fix_im[37] = WFFT_fix_im_37;
  assign WFFT_fix_im[38] = WFFT_fix_im_38;
  assign WFFT_fix_im[39] = WFFT_fix_im_39;
  assign WFFT_fix_im[40] = WFFT_fix_im_40;
  assign WFFT_fix_im[41] = WFFT_fix_im_41;
  assign WFFT_fix_im[42] = WFFT_fix_im_42;
  assign WFFT_fix_im[43] = WFFT_fix_im_43;
  assign WFFT_fix_im[44] = WFFT_fix_im_44;
  assign WFFT_fix_im[45] = WFFT_fix_im_45;
  assign WFFT_fix_im[46] = WFFT_fix_im_46;
  assign WFFT_fix_im[47] = WFFT_fix_im_47;
  assign WFFT_fix_im[48] = WFFT_fix_im_48;
  assign WFFT_fix_im[49] = WFFT_fix_im_49;
  assign WFFT_fix_im[50] = WFFT_fix_im_50;
  assign WFFT_fix_im[51] = WFFT_fix_im_51;
  assign WFFT_fix_im[52] = WFFT_fix_im_52;
  assign WFFT_fix_im[53] = WFFT_fix_im_53;
  assign WFFT_fix_im[54] = WFFT_fix_im_54;
  assign WFFT_fix_im[55] = WFFT_fix_im_55;
  assign WFFT_fix_im[56] = WFFT_fix_im_56;
  assign WFFT_fix_im[57] = WFFT_fix_im_57;
  assign WFFT_fix_im[58] = WFFT_fix_im_58;
  assign WFFT_fix_im[59] = WFFT_fix_im_59;
  assign WFFT_fix_im[60] = WFFT_fix_im_60;
  assign WFFT_fix_im[61] = WFFT_fix_im_61;
  assign WFFT_fix_im[62] = WFFT_fix_im_62;
  assign WFFT_fix_im[63] = WFFT_fix_im_63;
  assign WFFT_fix_im[64] = WFFT_fix_im_64;
  assign WFFT_fix_im[65] = WFFT_fix_im_65;
  assign WFFT_fix_im[66] = WFFT_fix_im_66;
  assign WFFT_fix_im[67] = WFFT_fix_im_67;
  assign WFFT_fix_im[68] = WFFT_fix_im_68;
  assign WFFT_fix_im[69] = WFFT_fix_im_69;
  assign WFFT_fix_im[70] = WFFT_fix_im_70;
  assign WFFT_fix_im[71] = WFFT_fix_im_71;
  assign WFFT_fix_im[72] = WFFT_fix_im_72;
  assign WFFT_fix_im[73] = WFFT_fix_im_73;
  assign WFFT_fix_im[74] = WFFT_fix_im_74;
  assign WFFT_fix_im[75] = WFFT_fix_im_75;
  assign WFFT_fix_im[76] = WFFT_fix_im_76;
  assign WFFT_fix_im[77] = WFFT_fix_im_77;
  assign WFFT_fix_im[78] = WFFT_fix_im_78;
  assign WFFT_fix_im[79] = WFFT_fix_im_79;
  assign WFFT_fix_im[80] = WFFT_fix_im_80;
  assign WFFT_fix_im[81] = WFFT_fix_im_81;
  assign WFFT_fix_im[82] = WFFT_fix_im_82;
  assign WFFT_fix_im[83] = WFFT_fix_im_83;
  assign WFFT_fix_im[84] = WFFT_fix_im_84;
  assign WFFT_fix_im[85] = WFFT_fix_im_85;
  assign WFFT_fix_im[86] = WFFT_fix_im_86;
  assign WFFT_fix_im[87] = WFFT_fix_im_87;
  assign WFFT_fix_im[88] = WFFT_fix_im_88;
  assign WFFT_fix_im[89] = WFFT_fix_im_89;
  assign WFFT_fix_im[90] = WFFT_fix_im_90;
  assign WFFT_fix_im[91] = WFFT_fix_im_91;
  assign WFFT_fix_im[92] = WFFT_fix_im_92;
  assign WFFT_fix_im[93] = WFFT_fix_im_93;
  assign WFFT_fix_im[94] = WFFT_fix_im_94;
  assign WFFT_fix_im[95] = WFFT_fix_im_95;
  assign WFFT_fix_im[96] = WFFT_fix_im_96;
  assign WFFT_fix_im[97] = WFFT_fix_im_97;
  assign WFFT_fix_im[98] = WFFT_fix_im_98;
  assign WFFT_fix_im[99] = WFFT_fix_im_99;
  assign WFFT_fix_im[100] = WFFT_fix_im_100;
  assign WFFT_fix_im[101] = WFFT_fix_im_101;
  assign WFFT_fix_im[102] = WFFT_fix_im_102;
  assign WFFT_fix_im[103] = WFFT_fix_im_103;
  assign WFFT_fix_im[104] = WFFT_fix_im_104;
  assign WFFT_fix_im[105] = WFFT_fix_im_105;
  assign WFFT_fix_im[106] = WFFT_fix_im_106;
  assign WFFT_fix_im[107] = WFFT_fix_im_107;
  assign WFFT_fix_im[108] = WFFT_fix_im_108;
  assign WFFT_fix_im[109] = WFFT_fix_im_109;
  assign WFFT_fix_im[110] = WFFT_fix_im_110;
  assign WFFT_fix_im[111] = WFFT_fix_im_111;
  assign WFFT_fix_im[112] = WFFT_fix_im_112;
  assign WFFT_fix_im[113] = WFFT_fix_im_113;
  assign WFFT_fix_im[114] = WFFT_fix_im_114;
  assign WFFT_fix_im[115] = WFFT_fix_im_115;
  assign WFFT_fix_im[116] = WFFT_fix_im_116;
  assign WFFT_fix_im[117] = WFFT_fix_im_117;
  assign WFFT_fix_im[118] = WFFT_fix_im_118;
  assign WFFT_fix_im[119] = WFFT_fix_im_119;
  assign WFFT_fix_im[120] = WFFT_fix_im_120;
  assign WFFT_fix_im[121] = WFFT_fix_im_121;
  assign WFFT_fix_im[122] = WFFT_fix_im_122;
  assign WFFT_fix_im[123] = WFFT_fix_im_123;
  assign WFFT_fix_im[124] = WFFT_fix_im_124;
  assign WFFT_fix_im[125] = WFFT_fix_im_125;
  assign WFFT_fix_im[126] = WFFT_fix_im_126;
  assign WFFT_fix_im[127] = WFFT_fix_im_127;
  assign WFFT_fix_im[128] = WFFT_fix_im_128;
  assign WFFT_fix_im[129] = WFFT_fix_im_129;
  assign WFFT_fix_im[130] = WFFT_fix_im_130;
  assign WFFT_fix_im[131] = WFFT_fix_im_131;
  assign WFFT_fix_im[132] = WFFT_fix_im_132;
  assign WFFT_fix_im[133] = WFFT_fix_im_133;
  assign WFFT_fix_im[134] = WFFT_fix_im_134;
  assign WFFT_fix_im[135] = WFFT_fix_im_135;
  assign WFFT_fix_im[136] = WFFT_fix_im_136;
  assign WFFT_fix_im[137] = WFFT_fix_im_137;
  assign WFFT_fix_im[138] = WFFT_fix_im_138;
  assign WFFT_fix_im[139] = WFFT_fix_im_139;
  assign WFFT_fix_im[140] = WFFT_fix_im_140;
  assign WFFT_fix_im[141] = WFFT_fix_im_141;
  assign WFFT_fix_im[142] = WFFT_fix_im_142;
  assign WFFT_fix_im[143] = WFFT_fix_im_143;
  assign WFFT_fix_im[144] = WFFT_fix_im_144;
  assign WFFT_fix_im[145] = WFFT_fix_im_145;
  assign WFFT_fix_im[146] = WFFT_fix_im_146;
  assign WFFT_fix_im[147] = WFFT_fix_im_147;
  assign WFFT_fix_im[148] = WFFT_fix_im_148;
  assign WFFT_fix_im[149] = WFFT_fix_im_149;
  assign WFFT_fix_im[150] = WFFT_fix_im_150;
  assign WFFT_fix_im[151] = WFFT_fix_im_151;
  assign WFFT_fix_im[152] = WFFT_fix_im_152;
  assign WFFT_fix_im[153] = WFFT_fix_im_153;
  assign WFFT_fix_im[154] = WFFT_fix_im_154;
  assign WFFT_fix_im[155] = WFFT_fix_im_155;
  assign WFFT_fix_im[156] = WFFT_fix_im_156;
  assign WFFT_fix_im[157] = WFFT_fix_im_157;
  assign WFFT_fix_im[158] = WFFT_fix_im_158;
  assign WFFT_fix_im[159] = WFFT_fix_im_159;
  assign WFFT_fix_im[160] = WFFT_fix_im_160;
  assign WFFT_fix_im[161] = WFFT_fix_im_161;
  assign WFFT_fix_im[162] = WFFT_fix_im_162;
  assign WFFT_fix_im[163] = WFFT_fix_im_163;
  assign WFFT_fix_im[164] = WFFT_fix_im_164;
  assign WFFT_fix_im[165] = WFFT_fix_im_165;
  assign WFFT_fix_im[166] = WFFT_fix_im_166;
  assign WFFT_fix_im[167] = WFFT_fix_im_167;
  assign WFFT_fix_im[168] = WFFT_fix_im_168;
  assign WFFT_fix_im[169] = WFFT_fix_im_169;
  assign WFFT_fix_im[170] = WFFT_fix_im_170;
  assign WFFT_fix_im[171] = WFFT_fix_im_171;
  assign WFFT_fix_im[172] = WFFT_fix_im_172;
  assign WFFT_fix_im[173] = WFFT_fix_im_173;
  assign WFFT_fix_im[174] = WFFT_fix_im_174;
  assign WFFT_fix_im[175] = WFFT_fix_im_175;
  assign WFFT_fix_im[176] = WFFT_fix_im_176;
  assign WFFT_fix_im[177] = WFFT_fix_im_177;
  assign WFFT_fix_im[178] = WFFT_fix_im_178;
  assign WFFT_fix_im[179] = WFFT_fix_im_179;
  assign WFFT_fix_im[180] = WFFT_fix_im_180;
  assign WFFT_fix_im[181] = WFFT_fix_im_181;
  assign WFFT_fix_im[182] = WFFT_fix_im_182;
  assign WFFT_fix_im[183] = WFFT_fix_im_183;
  assign WFFT_fix_im[184] = WFFT_fix_im_184;
  assign WFFT_fix_im[185] = WFFT_fix_im_185;
  assign WFFT_fix_im[186] = WFFT_fix_im_186;
  assign WFFT_fix_im[187] = WFFT_fix_im_187;
  assign WFFT_fix_im[188] = WFFT_fix_im_188;
  assign WFFT_fix_im[189] = WFFT_fix_im_189;
  assign WFFT_fix_im[190] = WFFT_fix_im_190;
  assign WFFT_fix_im[191] = WFFT_fix_im_191;
  assign WFFT_fix_im[192] = WFFT_fix_im_192;
  assign WFFT_fix_im[193] = WFFT_fix_im_193;
  assign WFFT_fix_im[194] = WFFT_fix_im_194;
  assign WFFT_fix_im[195] = WFFT_fix_im_195;
  assign WFFT_fix_im[196] = WFFT_fix_im_196;
  assign WFFT_fix_im[197] = WFFT_fix_im_197;
  assign WFFT_fix_im[198] = WFFT_fix_im_198;
  assign WFFT_fix_im[199] = WFFT_fix_im_199;
  assign WFFT_fix_im[200] = WFFT_fix_im_200;
  assign WFFT_fix_im[201] = WFFT_fix_im_201;
  assign WFFT_fix_im[202] = WFFT_fix_im_202;
  assign WFFT_fix_im[203] = WFFT_fix_im_203;
  assign WFFT_fix_im[204] = WFFT_fix_im_204;
  assign WFFT_fix_im[205] = WFFT_fix_im_205;
  assign WFFT_fix_im[206] = WFFT_fix_im_206;
  assign WFFT_fix_im[207] = WFFT_fix_im_207;
  assign WFFT_fix_im[208] = WFFT_fix_im_208;
  assign WFFT_fix_im[209] = WFFT_fix_im_209;
  assign WFFT_fix_im[210] = WFFT_fix_im_210;
  assign WFFT_fix_im[211] = WFFT_fix_im_211;
  assign WFFT_fix_im[212] = WFFT_fix_im_212;
  assign WFFT_fix_im[213] = WFFT_fix_im_213;
  assign WFFT_fix_im[214] = WFFT_fix_im_214;
  assign WFFT_fix_im[215] = WFFT_fix_im_215;
  assign WFFT_fix_im[216] = WFFT_fix_im_216;
  assign WFFT_fix_im[217] = WFFT_fix_im_217;
  assign WFFT_fix_im[218] = WFFT_fix_im_218;
  assign WFFT_fix_im[219] = WFFT_fix_im_219;
  assign WFFT_fix_im[220] = WFFT_fix_im_220;
  assign WFFT_fix_im[221] = WFFT_fix_im_221;
  assign WFFT_fix_im[222] = WFFT_fix_im_222;
  assign WFFT_fix_im[223] = WFFT_fix_im_223;
  assign WFFT_fix_im[224] = WFFT_fix_im_224;
  assign WFFT_fix_im[225] = WFFT_fix_im_225;
  assign WFFT_fix_im[226] = WFFT_fix_im_226;
  assign WFFT_fix_im[227] = WFFT_fix_im_227;
  assign WFFT_fix_im[228] = WFFT_fix_im_228;
  assign WFFT_fix_im[229] = WFFT_fix_im_229;
  assign WFFT_fix_im[230] = WFFT_fix_im_230;
  assign WFFT_fix_im[231] = WFFT_fix_im_231;
  assign WFFT_fix_im[232] = WFFT_fix_im_232;
  assign WFFT_fix_im[233] = WFFT_fix_im_233;
  assign WFFT_fix_im[234] = WFFT_fix_im_234;
  assign WFFT_fix_im[235] = WFFT_fix_im_235;
  assign WFFT_fix_im[236] = WFFT_fix_im_236;
  assign WFFT_fix_im[237] = WFFT_fix_im_237;
  assign WFFT_fix_im[238] = WFFT_fix_im_238;
  assign WFFT_fix_im[239] = WFFT_fix_im_239;
  assign WFFT_fix_im[240] = WFFT_fix_im_240;
  assign WFFT_fix_im[241] = WFFT_fix_im_241;
  assign WFFT_fix_im[242] = WFFT_fix_im_242;
  assign WFFT_fix_im[243] = WFFT_fix_im_243;
  assign WFFT_fix_im[244] = WFFT_fix_im_244;
  assign WFFT_fix_im[245] = WFFT_fix_im_245;
  assign WFFT_fix_im[246] = WFFT_fix_im_246;
  assign WFFT_fix_im[247] = WFFT_fix_im_247;
  assign WFFT_fix_im[248] = WFFT_fix_im_248;
  assign WFFT_fix_im[249] = WFFT_fix_im_249;
  assign WFFT_fix_im[250] = WFFT_fix_im_250;
  assign WFFT_fix_im[251] = WFFT_fix_im_251;

  assign s[0] = {1'b0, u[0]};
  assign add_temp[0] = s[0] + 10'b0000000001;
  assign y_re[0] = WFFT_fix_re[$signed({1'b0, add_temp[0]}) - 32'sd1];
  assign s_1[0] = {1'b0, u[0]};
  assign add_temp_1[0] = s_1[0] + 10'b0000000001;
  assign y_im[0] = WFFT_fix_im[$signed({1'b0, add_temp_1[0]}) - 32'sd1];
  assign s[1] = {1'b0, u[1]};
  assign add_temp[1] = s[1] + 10'b0000000001;
  assign y_re[1] = WFFT_fix_re[$signed({1'b0, add_temp[1]}) - 32'sd1];
  assign s_1[1] = {1'b0, u[1]};
  assign add_temp_1[1] = s_1[1] + 10'b0000000001;
  assign y_im[1] = WFFT_fix_im[$signed({1'b0, add_temp_1[1]}) - 32'sd1];
  assign s[2] = {1'b0, u[2]};
  assign add_temp[2] = s[2] + 10'b0000000001;
  assign y_re[2] = WFFT_fix_re[$signed({1'b0, add_temp[2]}) - 32'sd1];
  assign s_1[2] = {1'b0, u[2]};
  assign add_temp_1[2] = s_1[2] + 10'b0000000001;
  assign y_im[2] = WFFT_fix_im[$signed({1'b0, add_temp_1[2]}) - 32'sd1];
  assign s[3] = {1'b0, u[3]};
  assign add_temp[3] = s[3] + 10'b0000000001;
  assign y_re[3] = WFFT_fix_re[$signed({1'b0, add_temp[3]}) - 32'sd1];
  assign s_1[3] = {1'b0, u[3]};
  assign add_temp_1[3] = s_1[3] + 10'b0000000001;
  assign y_im[3] = WFFT_fix_im[$signed({1'b0, add_temp_1[3]}) - 32'sd1];
  assign s[4] = {1'b0, u[4]};
  assign add_temp[4] = s[4] + 10'b0000000001;
  assign y_re[4] = WFFT_fix_re[$signed({1'b0, add_temp[4]}) - 32'sd1];
  assign s_1[4] = {1'b0, u[4]};
  assign add_temp_1[4] = s_1[4] + 10'b0000000001;
  assign y_im[4] = WFFT_fix_im[$signed({1'b0, add_temp_1[4]}) - 32'sd1];
  assign s[5] = {1'b0, u[5]};
  assign add_temp[5] = s[5] + 10'b0000000001;
  assign y_re[5] = WFFT_fix_re[$signed({1'b0, add_temp[5]}) - 32'sd1];
  assign s_1[5] = {1'b0, u[5]};
  assign add_temp_1[5] = s_1[5] + 10'b0000000001;
  assign y_im[5] = WFFT_fix_im[$signed({1'b0, add_temp_1[5]}) - 32'sd1];



  assign y_re_0 = y_re[0];

  assign y_re_1 = y_re[1];

  assign y_re_2 = y_re[2];

  assign y_re_3 = y_re[3];

  assign y_re_4 = y_re[4];

  assign y_re_5 = y_re[5];

  assign y_im_0 = y_im[0];

  assign y_im_1 = y_im[1];

  assign y_im_2 = y_im[2];

  assign y_im_3 = y_im[3];

  assign y_im_4 = y_im[4];

  assign y_im_5 = y_im[5];

endmodule  // MATLAB_LOOT

